minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.1'
  - '@better-auth/drizzle-adapter@1.7.1'
  - '@better-auth/kysely-adapter@1.7.1'
  - '@better-auth/memory-adapter@1.7.1'
  - '@better-auth/mongo-adapter@1.7.1'
  - '@better-auth/prisma-adapter@1.7.1'
  - '@better-auth/telemetry@1.7.1'
  - '@lucide/svelte@1.32.0'
  - '@oxlint/binding-android-arm-eabi@1.79.0'
  - '@oxlint/binding-android-arm64@1.79.0'
  - '@oxlint/binding-darwin-arm64@1.79.0'
  - '@oxlint/binding-darwin-x64@1.79.0'
  - '@oxlint/binding-freebsd-x64@1.79.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.79.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.79.0'
  - '@oxlint/binding-linux-arm64-gnu@1.79.0'
  - '@oxlint/binding-linux-arm64-musl@1.79.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.79.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.79.0'
  - '@oxlint/binding-linux-riscv64-musl@1.79.0'
  - '@oxlint/binding-linux-s390x-gnu@1.79.0'
  - '@oxlint/binding-linux-x64-gnu@1.79.0'
  - '@oxlint/binding-linux-x64-musl@1.79.0'
  - '@oxlint/binding-openharmony-arm64@1.79.0'
  - '@oxlint/binding-win32-arm64-msvc@1.79.0'
  - '@oxlint/binding-win32-ia32-msvc@1.79.0'
  - '@oxlint/binding-win32-x64-msvc@1.79.0'
  - '@sveltejs/kit@2.70.3'
  - '@vitest/expect@4.1.11'
  - '@vitest/mocker@4.1.11'
  - '@vitest/pretty-format@4.1.11'
  - '@vitest/runner@4.1.11'
  - '@vitest/snapshot@4.1.11'
  - '@vitest/spy@4.1.11'
  - '@vitest/utils@4.1.11'
  - better-auth@1.7.1
  - oxlint@1.79.0
  - vitest@4.1.11
  - svelte@5.56.10
  - bits-ui@2.19.0
  - vite@8.2.2
