services:
  note-service:
    image: note-service
    build:
      context: .
      dockerfile: NoteService/Dockerfile
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: platform_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:

#  otel-collector:
#    image: otel/opentelemetry-collector:latest
#    ports:
#      - "4317:4317"
#      - "4318:4318"
#    volumes:
#      - ./otel-config.yaml:/etc/otel/config.yaml
#    command:
#      - "--config=/etc/otel/config.yaml"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge