// This file is auto-generated by @hey-api/openapi-ts

export const ApiProblemDetailsSchema = {
  required: [
    'code',
    'traceId'
  ],
  type: 'object',
  properties: {
    type: {
      type: [
        'null',
        'string'
      ]
    },
    title: {
      type: [
        'null',
        'string'
      ]
    },
    status: {
      type: [
        'null',
        'integer'
      ],
      format: 'int32'
    },
    detail: {
      type: [
        'null',
        'string'
      ]
    },
    instance: {
      type: [
        'null',
        'string'
      ]
    },
    code: {
      type: 'string'
    },
    traceId: {
      type: 'string'
    }
  }
} as const;

export const ApiValidationProblemDetailsSchema = {
  required: [
    'code',
    'errors',
    'traceId'
  ],
  type: 'object',
  properties: {
    type: {
      type: [
        'null',
        'string'
      ]
    },
    title: {
      type: [
        'null',
        'string'
      ]
    },
    status: {
      type: [
        'null',
        'integer'
      ],
      format: 'int32'
    },
    detail: {
      type: [
        'null',
        'string'
      ]
    },
    instance: {
      type: [
        'null',
        'string'
      ]
    },
    code: {
      type: 'string'
    },
    errors: {
      type: 'object',
      additionalProperties: {
        required: [
          'code',
          'message',
          'parameters'
        ],
        type: 'object',
        properties: {
          code: {
            type: 'string'
          },
          message: {
            type: 'string'
          },
          parameters: {
            type: 'array',
            items: {
              type: 'string'
            }
          }
        }
      }
    },
    traceId: {
      type: 'string'
    }
  }
} as const;

export const ApprovedHeaderPostDeletionForbiddenErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ApprovedHeaderPostDeletionForbiddenError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const AuthenticationRequiredErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'AuthenticationRequiredError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const CategoryDtoSchema = {
  required: [
    'categoryId',
    'forumId',
    'title',
    'createdBy',
    'createdAt'
  ],
  type: 'object',
  properties: {
    categoryId: {
      $ref: '#/components/schemas/CategoryId'
    },
    forumId: {
      $ref: '#/components/schemas/ForumId'
    },
    title: {
      $ref: '#/components/schemas/CategoryTitle'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const CategoryIdSchema = {
  pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
  type: 'string',
  format: 'uuid',
  'x-value-object': 'CategoryId'
} as const;

export const CategoryNotFoundErrorSchema = {
  required: [
    'categoryId',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'CategoryNotFoundError',
      type: 'string',
      readOnly: true
    },
    categoryId: {
      $ref: '#/components/schemas/CategoryId'
    }
  }
} as const;

export const CategoryTitleSchema = {
  maxLength: 128,
  minLength: 3,
  pattern: '^(?!\\s*$).+',
  type: 'string',
  'x-value-object': 'CategoryTitle'
} as const;

export const ClaimNotFoundErrorSchema = {
  required: [
    'claimName',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ClaimNotFoundError',
      type: 'string',
      readOnly: true
    },
    claimName: {
      type: 'string'
    }
  }
} as const;

export const CountSchema = {
  maximum: 2147483647,
  minimum: 0,
  type: 'integer',
  'x-value-object': 'Count'
} as const;

export const CreateCategoryRequestBodySchema = {
  required: [
    'forumId',
    'title'
  ],
  type: 'object',
  properties: {
    forumId: {
      $ref: '#/components/schemas/ForumId'
    },
    title: {
      $ref: '#/components/schemas/CategoryTitle'
    }
  }
} as const;

export const CreateForumRequestBodySchema = {
  required: [
    'title'
  ],
  type: 'object',
  properties: {
    title: {
      $ref: '#/components/schemas/ForumTitle'
    }
  }
} as const;

export const CreatePostRequestBodySchema = {
  required: [
    'content'
  ],
  type: 'object',
  properties: {
    content: {
      $ref: '#/components/schemas/PostContent'
    }
  }
} as const;

export const CreateThreadRequestBodySchema = {
  required: [
    'categoryId',
    'title'
  ],
  type: 'object',
  properties: {
    categoryId: {
      $ref: '#/components/schemas/CategoryId'
    },
    title: {
      $ref: '#/components/schemas/ThreadTitle'
    }
  }
} as const;

export const DuplicatePostBookmarkErrorSchema = {
  required: [
    'userId',
    'postId',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'DuplicatePostBookmarkError',
      type: 'string',
      readOnly: true
    },
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    }
  }
} as const;

export const ForumDtoSchema = {
  required: [
    'forumId',
    'title',
    'createdBy',
    'createdAt'
  ],
  type: 'object',
  properties: {
    forumId: {
      $ref: '#/components/schemas/ForumId'
    },
    title: {
      $ref: '#/components/schemas/ForumTitle'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const ForumIdSchema = {
  pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
  type: 'string',
  format: 'uuid',
  'x-value-object': 'ForumId'
} as const;

export const ForumNotFoundErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ForumNotFoundError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const ForumTitleSchema = {
  maxLength: 64,
  minLength: 3,
  pattern: '^(?!\\s*$).+',
  type: 'string',
  'x-value-object': 'ForumTitle'
} as const;

export const GetBookmarkedPostIdsResponseSchema = {
  required: [
    'postIds'
  ],
  type: 'object',
  properties: {
    postIds: {
      type: 'array',
      items: {
        pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
        type: 'string',
        format: 'uuid',
        'x-value-object': 'PostId'
      }
    }
  }
} as const;

export const GetBookmarkedPostsPagedQuerySortTypeSchema = {
  enum: [
    'createdAt',
    '-createdAt'
  ],
  type: 'string',
  'x-enum-varnames': [
    'CREATED_AT_ASC',
    'CREATED_AT_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by CreatedAt ascending',
    'Sort by CreatedAt descending'
  ]
} as const;

export const GetCategoriesPagedQuerySortTypeSchema = {
  enum: [
    'categoryId',
    'forumId',
    '-categoryId',
    '-forumId'
  ],
  type: 'string',
  'x-enum-varnames': [
    'CATEGORY_ID_ASC',
    'FORUM_ID_ASC',
    'CATEGORY_ID_DESC',
    'FORUM_ID_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by CategoryId ascending',
    'Sort by ForumId ascending',
    'Sort by CategoryId descending',
    'Sort by ForumId descending'
  ]
} as const;

export const GetCategoryThreadsPagedQuerySortTypeSchema = {
  enum: [
    'activity',
    '-activity'
  ],
  type: 'string',
  'x-enum-varnames': [
    'ACTIVITY_ASC',
    'ACTIVITY_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by Activity ascending',
    'Sort by Activity descending'
  ]
} as const;

export const GetForumsPagedQuerySortTypeSchema = {
  enum: [
    'forumId',
    '-forumId'
  ],
  type: 'string',
  'x-enum-varnames': [
    'FORUM_ID_ASC',
    'FORUM_ID_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by ForumId ascending',
    'Sort by ForumId descending'
  ]
} as const;

export const GetThreadPostsPagedQuerySortTypeSchema = {
  enum: [
    'index',
    '-index'
  ],
  type: 'string',
  'x-enum-varnames': [
    'INDEX_ASC',
    'INDEX_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by Index ascending',
    'Sort by Index descending'
  ]
} as const;

export const GetThreadsPagedQuerySortTypeSchema = {
  enum: [
    'threadId',
    '-threadId'
  ],
  type: 'string',
  'x-enum-varnames': [
    'THREAD_ID_ASC',
    'THREAD_ID_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by ThreadId ascending',
    'Sort by ThreadId descending'
  ]
} as const;

export const IndexSchema = {
  maximum: 2147483647,
  minimum: 0,
  type: 'integer',
  'x-value-object': 'Index'
} as const;

export const InsufficientRoleToEditHeaderPostErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'InsufficientRoleToEditHeaderPostError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const InvalidPostContentErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'InvalidPostContentError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const InvalidSearchCursorErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'InvalidSearchCursorError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const InvalidSearchPaginationErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'InvalidSearchPaginationError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const LocaleRequiredErrorSchema = {
  required: [
    'supportedLocales',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'LocaleRequiredError',
      type: 'string',
      readOnly: true
    },
    supportedLocales: {
      type: 'array',
      items: {
        type: 'string'
      }
    }
  }
} as const;

export const NonPostAuthorErrorSchema = {
  required: [
    'threadId',
    'postId',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'NonPostAuthorError',
      type: 'string',
      readOnly: true
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    }
  }
} as const;

export const NonThreadOwnerErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'NonThreadOwnerError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const NotAdminErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'NotAdminError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const PaginationLimitMin10Max100Schema = {
  maximum: 100,
  minimum: 10,
  type: 'integer',
  'x-value-object': 'PaginationLimitMin10Max100'
} as const;

export const PaginationOffsetSchema = {
  maximum: 2147483647,
  minimum: 0,
  type: 'integer',
  default: 0,
  'x-value-object': 'PaginationOffset'
} as const;

export const PermissionDeniedErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'PermissionDeniedError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const PostBookmarkNotFoundErrorSchema = {
  required: [
    'userId',
    'postId',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'PostBookmarkNotFoundError',
      type: 'string',
      readOnly: true
    },
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    }
  }
} as const;

export const PostContentSchema = {
  maxLength: 1024,
  minLength: 2,
  pattern: '^(?!\\s*$).+',
  type: 'string',
  'x-value-object': 'PostContent'
} as const;

export const PostDtoSchema = {
  required: [
    'postId',
    'threadId',
    'content',
    'createdBy',
    'createdAt',
    'updatedBy',
    'updatedAt',
    'rowVersion'
  ],
  type: 'object',
  properties: {
    postId: {
      $ref: '#/components/schemas/PostId'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    content: {
      $ref: '#/components/schemas/PostContent'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    },
    updatedBy: {
      $ref: '#/components/schemas/UserId'
    },
    updatedAt: {
      type: 'string',
      format: 'date-time'
    },
    rowVersion: {
      $ref: '#/components/schemas/RowVersion'
    }
  }
} as const;

export const PostIdSchema = {
  pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
  type: 'string',
  format: 'uuid',
  'x-value-object': 'PostId'
} as const;

export const PostLimitReachedErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'PostLimitReachedError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const PostNotFoundErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'PostNotFoundError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const PostStaleErrorSchema = {
  required: [
    'threadId',
    'postId',
    'rowVersion',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'PostStaleError',
      type: 'string',
      readOnly: true
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    },
    rowVersion: {
      $ref: '#/components/schemas/RowVersion'
    }
  }
} as const;

export const RowVersionSchema = {
  maximum: 4294967295,
  minimum: 0,
  type: 'integer',
  format: 'uint32',
  'x-value-object': 'RowVersion'
} as const;

export const SearchCursorSchema = {} as const;

export const SearchQuerySortTypeSchema = {
  enum: [
    'relevance',
    'newest',
    '-relevance',
    '-newest'
  ],
  type: 'string',
  'x-enum-varnames': [
    'RELEVANCE_ASC',
    'NEWEST_ASC',
    'RELEVANCE_DESC',
    'NEWEST_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by Relevance ascending',
    'Sort by Newest ascending',
    'Sort by Relevance descending',
    'Sort by Newest descending'
  ]
} as const;

export const SearchResultDtoSchema = {
  required: [
    'type',
    'forumTitle',
    'categoryId',
    'categoryTitle',
    'threadId',
    'threadTitle',
    'postId',
    'snippet',
    'forumId',
    'createdBy',
    'createdAt'
  ],
  type: 'object',
  properties: {
    type: {
      $ref: '#/components/schemas/SearchResultType'
    },
    forumTitle: {
      $ref: '#/components/schemas/ForumTitle'
    },
    categoryId: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/CategoryId'
        }
      ]
    },
    categoryTitle: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/CategoryTitle'
        }
      ]
    },
    threadId: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/ThreadId'
        }
      ]
    },
    threadTitle: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/ThreadTitle'
        }
      ]
    },
    postId: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/PostId'
        }
      ]
    },
    snippet: {
      type: [
        'null',
        'string'
      ]
    },
    forumId: {
      $ref: '#/components/schemas/ForumId'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const SearchResultsDtoSchema = {
  required: [
    'items',
    'nextCursor'
  ],
  type: 'object',
  properties: {
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/SearchResultDto'
      }
    },
    nextCursor: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/SearchCursor'
        }
      ]
    }
  }
} as const;

export const SearchResultTypeSchema = {
  enum: [
    'forum',
    'category',
    'thread',
    'post'
  ],
  type: 'string',
  'x-enum-varnames': [
    'FORUM',
    'CATEGORY',
    'THREAD',
    'POST'
  ]
} as const;

export const SearchTermSchema = {
  maxLength: 100,
  minLength: 2,
  pattern: '^(?!\\s*$).+',
  type: 'string',
  'x-value-object': 'SearchTerm'
} as const;

export const ThreadDtoSchema = {
  required: [
    'threadId',
    'categoryId',
    'title',
    'createdBy',
    'createdAt',
    'state',
    'postCount'
  ],
  type: 'object',
  properties: {
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    categoryId: {
      $ref: '#/components/schemas/CategoryId'
    },
    title: {
      $ref: '#/components/schemas/ThreadTitle'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    },
    state: {
      $ref: '#/components/schemas/ThreadState'
    },
    postCount: {
      $ref: '#/components/schemas/Count'
    },
    lastHeaderPostId: {
      oneOf: [
        {
          type: 'null'
        },
        {
          $ref: '#/components/schemas/PostId'
        }
      ]
    }
  }
} as const;

export const ThreadIdSchema = {
  pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
  type: 'string',
  format: 'uuid',
  'x-value-object': 'ThreadId'
} as const;

export const ThreadLockedByStateErrorSchema = {
  required: [
    'state',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ThreadLockedByStateError',
      type: 'string',
      readOnly: true
    },
    state: {
      $ref: '#/components/schemas/ThreadState'
    }
  }
} as const;

export const ThreadMustContainPostsErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ThreadMustContainPostsError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const ThreadNotFoundErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ThreadNotFoundError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const ThreadNotInStateErrorSchema = {
  required: [
    'state',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ThreadNotInStateError',
      type: 'string',
      readOnly: true
    },
    state: {
      $ref: '#/components/schemas/ThreadState'
    }
  }
} as const;

export const ThreadStateSchema = {
  enum: [
    'draft',
    'pendingApproval',
    'approved'
  ],
  type: 'string',
  'x-enum-varnames': [
    'DRAFT',
    'PENDING_APPROVAL',
    'APPROVED'
  ]
} as const;

export const ThreadTitleSchema = {
  maxLength: 128,
  minLength: 3,
  pattern: '^(?!\\s*$).+',
  type: 'string',
  'x-value-object': 'ThreadTitle'
} as const;

export const UnsupportedLocaleErrorSchema = {
  required: [
    'supportedLocales',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'UnsupportedLocaleError',
      type: 'string',
      readOnly: true
    },
    supportedLocales: {
      type: 'array',
      items: {
        type: 'string'
      }
    }
  }
} as const;

export const UpdatePostRequestBodySchema = {
  required: [
    'content',
    'rowVersion'
  ],
  type: 'object',
  properties: {
    content: {
      $ref: '#/components/schemas/PostContent'
    },
    rowVersion: {
      $ref: '#/components/schemas/RowVersion'
    }
  }
} as const;

export const UserIdSchema = {
  pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
  type: 'string',
  format: 'uuid',
  'x-value-object': 'UserId'
} as const;

export const IFormFileSchema = {
  type: 'string',
  format: 'binary'
} as const;

export const InvalidAvatarFileSizeErrorSchema = {
  required: [
    'minimumFileSize',
    'maximumFileSize',
    'actualFileSize',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'InvalidAvatarFileSizeError',
      type: 'string',
      readOnly: true
    },
    minimumFileSize: {
      type: 'integer',
      format: 'int64'
    },
    maximumFileSize: {
      type: 'integer',
      format: 'int64'
    },
    actualFileSize: {
      type: 'integer',
      format: 'int64'
    }
  }
} as const;

export const InvalidAvatarFileTypeErrorSchema = {
  required: [
    'expectedMediaType',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'InvalidAvatarFileTypeError',
      type: 'string',
      readOnly: true
    },
    expectedMediaType: {
      type: 'string'
    }
  }
} as const;

export const ChannelTypeSchema = {
  enum: [
    'internal',
    'email'
  ],
  type: 'string',
  'x-enum-varnames': [
    'INTERNAL',
    'EMAIL'
  ]
} as const;

export const CreateThreadSubscriptionRequestBodySchema = {
  required: [
    'channels'
  ],
  type: 'object',
  properties: {
    channels: {
      minItems: 1,
      uniqueItems: true,
      type: 'array',
      items: {
        $ref: '#/components/schemas/ChannelType'
      }
    }
  }
} as const;

export const DuplicateThreadSubscriptionErrorSchema = {
  required: [
    'userId',
    'threadId',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'DuplicateThreadSubscriptionError',
      type: 'string',
      readOnly: true
    },
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    }
  }
} as const;

export const GetInternalNotificationsPagedQuerySortTypeSchema = {
  enum: [
    'occurredAt',
    'deliveredAt',
    '-occurredAt',
    '-deliveredAt'
  ],
  type: 'string',
  'x-enum-varnames': [
    'OCCURRED_AT_ASC',
    'DELIVERED_AT_ASC',
    'OCCURRED_AT_DESC',
    'DELIVERED_AT_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by OccurredAt ascending',
    'Sort by DeliveredAt ascending',
    'Sort by OccurredAt descending',
    'Sort by DeliveredAt descending'
  ]
} as const;

export const GetThreadSubscriptionLatestEventsPagedQuerySortTypeSchema = {
  enum: [
    'latestEvent',
    'threadId',
    '-latestEvent',
    '-threadId'
  ],
  type: 'string',
  'x-enum-varnames': [
    'LATEST_EVENT_ASC',
    'THREAD_ID_ASC',
    'LATEST_EVENT_DESC',
    'THREAD_ID_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by LatestEvent ascending',
    'Sort by ThreadId ascending',
    'Sort by LatestEvent descending',
    'Sort by ThreadId descending'
  ]
} as const;

export const GetThreadSubscriptionsPagedQuerySortTypeSchema = {
  enum: [
    'threadId',
    '-threadId'
  ],
  type: 'string',
  'x-enum-varnames': [
    'THREAD_ID_ASC',
    'THREAD_ID_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by ThreadId ascending',
    'Sort by ThreadId descending'
  ]
} as const;

export const GetThreadSubscriptionStatusQueryResultSchema = {
  required: [
    'isSubscribed'
  ],
  type: 'object',
  properties: {
    isSubscribed: {
      type: 'boolean',
      description: 'Подписан ли пользователь на тему'
    }
  }
} as const;

export const InternalNotificationDtoSchema = {
  required: [
    'notifiableEventId',
    'payload',
    'occurredAt'
  ],
  type: 'object',
  properties: {
    notifiableEventId: {
      $ref: '#/components/schemas/NotifiableEventId'
    },
    payload: {
      $ref: '#/components/schemas/NotifiableEventPayload'
    },
    occurredAt: {
      type: 'string',
      format: 'date-time'
    },
    deliveredAt: {
      type: [
        'null',
        'string'
      ],
      format: 'date-time'
    }
  }
} as const;

export const InternalNotificationsPagedDtoSchema = {
  required: [
    'notifications',
    'threads',
    'users',
    'totalCount'
  ],
  type: 'object',
  properties: {
    notifications: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/InternalNotificationDto'
      }
    },
    threads: {
      propertyNames: {
        $ref: '#/components/schemas/ThreadId'
      },
      type: 'object',
      additionalProperties: {
        $ref: '#/components/schemas/ThreadTitle'
      }
    },
    users: {
      propertyNames: {
        $ref: '#/components/schemas/UserId'
      },
      type: 'object',
      additionalProperties: {
        $ref: '#/components/schemas/Username'
      }
    },
    totalCount: {
      description: 'Общее количество уведомлений с учетом фильтрации',
      $ref: '#/components/schemas/Count'
    }
  }
} as const;

export const NotifiableEventIdSchema = {
  pattern: '^(?!00000000-0000-0000-0000-000000000000$)',
  type: 'string',
  format: 'uuid',
  'x-value-object': 'NotifiableEventId'
} as const;

export const NotifiableEventPayloadSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  anyOf: [
    {
      $ref: '#/components/schemas/NotifiableEventPayloadPostAddedNotifiableEventPayload'
    },
    {
      $ref: '#/components/schemas/NotifiableEventPayloadPostUpdatedNotifiableEventPayload'
    },
    {
      $ref: '#/components/schemas/NotifiableEventPayloadThreadApprovedNotifiableEventPayload'
    },
    {
      $ref: '#/components/schemas/NotifiableEventPayloadThreadRejectedNotifiableEventPayload'
    }
  ],
  discriminator: {
    propertyName: '$type',
    mapping: {
      PostAdded: '#/components/schemas/NotifiableEventPayloadPostAddedNotifiableEventPayload',
      PostUpdated: '#/components/schemas/NotifiableEventPayloadPostUpdatedNotifiableEventPayload',
      ThreadApproved: '#/components/schemas/NotifiableEventPayloadThreadApprovedNotifiableEventPayload',
      ThreadRejected: '#/components/schemas/NotifiableEventPayloadThreadRejectedNotifiableEventPayload'
    }
  }
} as const;

export const NotifiableEventPayloadPostAddedNotifiableEventPayloadSchema = {
  required: [
    'threadId',
    'postId',
    'createdBy',
    '$type'
  ],
  properties: {
    $type: {
      enum: [
        'PostAdded'
      ],
      type: 'string'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    }
  }
} as const;

export const NotifiableEventPayloadPostUpdatedNotifiableEventPayloadSchema = {
  required: [
    'threadId',
    'postId',
    'updatedBy',
    '$type'
  ],
  properties: {
    $type: {
      enum: [
        'PostUpdated'
      ],
      type: 'string'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    },
    updatedBy: {
      $ref: '#/components/schemas/UserId'
    }
  }
} as const;

export const NotifiableEventPayloadThreadApprovedNotifiableEventPayloadSchema = {
  required: [
    'threadId',
    'createdBy',
    'approvedBy',
    'approvedAt',
    '$type'
  ],
  properties: {
    $type: {
      enum: [
        'ThreadApproved'
      ],
      type: 'string'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    approvedBy: {
      $ref: '#/components/schemas/UserId'
    },
    approvedAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const NotifiableEventPayloadThreadRejectedNotifiableEventPayloadSchema = {
  required: [
    'threadId',
    'createdBy',
    'rejectedBy',
    'rejectedAt',
    '$type'
  ],
  properties: {
    $type: {
      enum: [
        'ThreadRejected'
      ],
      type: 'string'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    createdBy: {
      $ref: '#/components/schemas/UserId'
    },
    rejectedBy: {
      $ref: '#/components/schemas/UserId'
    },
    rejectedAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const NotificationNotFoundErrorSchema = {
  required: [
    'userId',
    'notifiableEventId',
    'channel',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'NotificationNotFoundError',
      type: 'string',
      readOnly: true
    },
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    notifiableEventId: {
      $ref: '#/components/schemas/NotifiableEventId'
    },
    channel: {
      $ref: '#/components/schemas/ChannelType'
    }
  }
} as const;

export const PagedListOfThreadDtoSchema = {
  required: [
    'items',
    'totalCount'
  ],
  type: 'object',
  properties: {
    items: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/ThreadDto'
      }
    },
    totalCount: {
      $ref: '#/components/schemas/Count'
    }
  }
} as const;

export const ThreadSubscriptionLatestEventDtoSchema = {
  required: [
    'notifiableEventId',
    'payload',
    'occurredAt'
  ],
  type: 'object',
  properties: {
    notifiableEventId: {
      $ref: '#/components/schemas/NotifiableEventId'
    },
    payload: {
      $ref: '#/components/schemas/NotifiableEventPayload'
    },
    occurredAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const ThreadSubscriptionNotFoundErrorSchema = {
  required: [
    'userId',
    'threadId',
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'ThreadSubscriptionNotFoundError',
      type: 'string',
      readOnly: true
    },
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    }
  }
} as const;

export const UsernameSchema = {
  maxLength: 64,
  minLength: 3,
  pattern: '^[a-z0-9]+(_[a-z0-9]+)*$',
  type: 'string',
  'x-value-object': 'Username'
} as const;

export const ChangeCurrentUserLocaleRequestBodySchema = {
  required: [
    'locale'
  ],
  type: 'object',
  properties: {
    locale: {
      $ref: '#/components/schemas/Locale'
    }
  }
} as const;

export const GetUsersPagedQuerySortTypeSchema = {
  enum: [
    'userId',
    '-userId'
  ],
  type: 'string',
  'x-enum-varnames': [
    'USER_ID_ASC',
    'USER_ID_DESC'
  ],
  'x-enum-descriptions': [
    'Sort by UserId ascending',
    'Sort by UserId descending'
  ]
} as const;

export const LocaleSchema = {
  maxLength: 2,
  minLength: 2,
  pattern: '^(en|ru)$',
  enum: [
    'en',
    'ru'
  ],
  type: 'string',
  'x-value-object': 'Locale'
} as const;

export const UserDtoSchema = {
  required: [
    'userId',
    'username',
    'email',
    'enabled',
    'createdAt'
  ],
  type: 'object',
  properties: {
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    username: {
      $ref: '#/components/schemas/Username'
    },
    email: {
      type: 'string'
    },
    enabled: {
      type: 'boolean'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    }
  }
} as const;

export const UserNotFoundErrorSchema = {
  required: [
    '$type'
  ],
  type: 'object',
  properties: {
    $type: {
      const: 'UserNotFoundError',
      type: 'string',
      readOnly: true
    }
  }
} as const;

export const CategoryNotFoundErrorWritableSchema = {
  required: [
    'categoryId'
  ],
  type: 'object',
  properties: {
    categoryId: {
      $ref: '#/components/schemas/CategoryId'
    }
  }
} as const;

export const ClaimNotFoundErrorWritableSchema = {
  required: [
    'claimName'
  ],
  type: 'object',
  properties: {
    claimName: {
      type: 'string'
    }
  }
} as const;

export const DuplicatePostBookmarkErrorWritableSchema = {
  required: [
    'userId',
    'postId'
  ],
  type: 'object',
  properties: {
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    }
  }
} as const;

export const LocaleRequiredErrorWritableSchema = {
  required: [
    'supportedLocales'
  ],
  type: 'object',
  properties: {
    supportedLocales: {
      type: 'array',
      items: {
        type: 'string'
      }
    }
  }
} as const;

export const NonPostAuthorErrorWritableSchema = {
  required: [
    'threadId',
    'postId'
  ],
  type: 'object',
  properties: {
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    }
  }
} as const;

export const PostBookmarkNotFoundErrorWritableSchema = {
  required: [
    'userId',
    'postId'
  ],
  type: 'object',
  properties: {
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    }
  }
} as const;

export const PostStaleErrorWritableSchema = {
  required: [
    'threadId',
    'postId',
    'rowVersion'
  ],
  type: 'object',
  properties: {
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    },
    postId: {
      $ref: '#/components/schemas/PostId'
    },
    rowVersion: {
      $ref: '#/components/schemas/RowVersion'
    }
  }
} as const;

export const ThreadLockedByStateErrorWritableSchema = {
  required: [
    'state'
  ],
  type: 'object',
  properties: {
    state: {
      $ref: '#/components/schemas/ThreadState'
    }
  }
} as const;

export const ThreadNotInStateErrorWritableSchema = {
  required: [
    'state'
  ],
  type: 'object',
  properties: {
    state: {
      $ref: '#/components/schemas/ThreadState'
    }
  }
} as const;

export const UnsupportedLocaleErrorWritableSchema = {
  required: [
    'supportedLocales'
  ],
  type: 'object',
  properties: {
    supportedLocales: {
      type: 'array',
      items: {
        type: 'string'
      }
    }
  }
} as const;

export const InvalidAvatarFileSizeErrorWritableSchema = {
  required: [
    'minimumFileSize',
    'maximumFileSize',
    'actualFileSize'
  ],
  type: 'object',
  properties: {
    minimumFileSize: {
      type: 'integer',
      format: 'int64'
    },
    maximumFileSize: {
      type: 'integer',
      format: 'int64'
    },
    actualFileSize: {
      type: 'integer',
      format: 'int64'
    }
  }
} as const;

export const InvalidAvatarFileTypeErrorWritableSchema = {
  required: [
    'expectedMediaType'
  ],
  type: 'object',
  properties: {
    expectedMediaType: {
      type: 'string'
    }
  }
} as const;

export const DuplicateThreadSubscriptionErrorWritableSchema = {
  required: [
    'userId',
    'threadId'
  ],
  type: 'object',
  properties: {
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    }
  }
} as const;

export const NotificationNotFoundErrorWritableSchema = {
  required: [
    'userId',
    'notifiableEventId',
    'channel'
  ],
  type: 'object',
  properties: {
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    notifiableEventId: {
      $ref: '#/components/schemas/NotifiableEventId'
    },
    channel: {
      $ref: '#/components/schemas/ChannelType'
    }
  }
} as const;

export const ThreadSubscriptionNotFoundErrorWritableSchema = {
  required: [
    'userId',
    'threadId'
  ],
  type: 'object',
  properties: {
    userId: {
      $ref: '#/components/schemas/UserId'
    },
    threadId: {
      $ref: '#/components/schemas/ThreadId'
    }
  }
} as const;
