// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { GetCategoriesData, GetCategoriesResponse, CreateCategoryData, CreateCategoryResponse, GetCategoryData, GetCategoryResponse, GetCategoryError, GetCategoriesPostsCountData, GetCategoriesPostsCountResponse, GetCategoriesPostsLatestData, GetCategoriesPostsLatestResponse, GetCategoryThreadsCountData, GetCategoryThreadsCountResponse, GetCategoryThreadsData, GetCategoryThreadsResponse, GetForumsCountData, GetForumsCountResponse, GetForumsData, GetForumsResponse, CreateForumData, CreateForumResponse, GetForumData, GetForumResponse, GetForumError, GetForumCategoriesCountData, GetForumCategoriesCountResponse, GetForumsCategoriesLatestByPostData, GetForumsCategoriesLatestByPostResponse, GetPostsData, GetPostsResponse, GetThreadData, GetThreadResponse, GetThreadError, GetThreadPostsCountData, GetThreadPostsCountResponse, GetThreadPostsLatestData, GetThreadPostsLatestResponse, CreateThreadData, CreateThreadResponse, CreatePostData, CreatePostResponse, DeleteAvatarData, UploadAvatarData, UploadAvatarError, GetUsersData, GetUsersResponse, GetUsersError, GetUserByIdData, GetUserByIdResponse, GetUserByIdError, GetUsersByIdsData, GetUsersByIdsResponse } from './types.gen';
import { getCategoriesResponseTransformer, getCategoryResponseTransformer, getCategoryThreadsResponseTransformer, getForumsCountResponseTransformer, getForumsResponseTransformer, getForumResponseTransformer, getPostsResponseTransformer, getThreadResponseTransformer, getThreadPostsLatestResponseTransformer, createPostResponseTransformer, getUsersResponseTransformer, getUserByIdResponseTransformer, getUsersByIdsResponseTransformer } from './transformers.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCategoriesResponse, unknown, ThrowOnError>({
        responseTransformer: getCategoriesResponseTransformer,
        url: '/api/categories',
        ...options
    });
};

export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCategoryResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getCategory = <ThrowOnError extends boolean = false>(options: Options<GetCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoryResponse, GetCategoryError, ThrowOnError>({
        responseTransformer: getCategoryResponseTransformer,
        url: '/api/categories/{categoryId}',
        ...options
    });
};

export const getCategoriesPostsCount = <ThrowOnError extends boolean = false>(options: Options<GetCategoriesPostsCountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoriesPostsCountResponse, unknown, ThrowOnError>({
        url: '/api/categories/{categoryIds}/posts/count',
        ...options
    });
};

export const getCategoriesPostsLatest = <ThrowOnError extends boolean = false>(options: Options<GetCategoriesPostsLatestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoriesPostsLatestResponse, unknown, ThrowOnError>({
        url: '/api/categories/{categoryIds}/posts/latest',
        ...options
    });
};

export const getCategoryThreadsCount = <ThrowOnError extends boolean = false>(options: Options<GetCategoryThreadsCountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoryThreadsCountResponse, unknown, ThrowOnError>({
        url: '/api/categories/{categoryIds}/threads/count',
        ...options
    });
};

export const getCategoryThreads = <ThrowOnError extends boolean = false>(options: Options<GetCategoryThreadsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoryThreadsResponse, unknown, ThrowOnError>({
        responseTransformer: getCategoryThreadsResponseTransformer,
        url: '/api/categories/{categoryId}/threads',
        ...options
    });
};

export const getForumsCount = <ThrowOnError extends boolean = false>(options?: Options<GetForumsCountData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetForumsCountResponse, unknown, ThrowOnError>({
        responseTransformer: getForumsCountResponseTransformer,
        url: '/api/forums/count',
        ...options
    });
};

export const getForums = <ThrowOnError extends boolean = false>(options?: Options<GetForumsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetForumsResponse, unknown, ThrowOnError>({
        responseTransformer: getForumsResponseTransformer,
        url: '/api/forums',
        ...options
    });
};

export const createForum = <ThrowOnError extends boolean = false>(options: Options<CreateForumData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateForumResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/forums',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getForum = <ThrowOnError extends boolean = false>(options: Options<GetForumData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetForumResponse, GetForumError, ThrowOnError>({
        responseTransformer: getForumResponseTransformer,
        url: '/api/forums/{forumId}',
        ...options
    });
};

export const getForumCategoriesCount = <ThrowOnError extends boolean = false>(options: Options<GetForumCategoriesCountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetForumCategoriesCountResponse, unknown, ThrowOnError>({
        url: '/api/forums/{forumIds}/categories/count',
        ...options
    });
};

export const getForumsCategoriesLatestByPost = <ThrowOnError extends boolean = false>(options: Options<GetForumsCategoriesLatestByPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetForumsCategoriesLatestByPostResponse, unknown, ThrowOnError>({
        url: '/api/forums/{forumIds}/categories/latest-by-post',
        ...options
    });
};

export const getPosts = <ThrowOnError extends boolean = false>(options?: Options<GetPostsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPostsResponse, unknown, ThrowOnError>({
        responseTransformer: getPostsResponseTransformer,
        url: '/api/posts',
        ...options
    });
};

export const getThread = <ThrowOnError extends boolean = false>(options: Options<GetThreadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetThreadResponse, GetThreadError, ThrowOnError>({
        responseTransformer: getThreadResponseTransformer,
        url: '/api/threads/{threadId}',
        ...options
    });
};

export const getThreadPostsCount = <ThrowOnError extends boolean = false>(options: Options<GetThreadPostsCountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetThreadPostsCountResponse, unknown, ThrowOnError>({
        url: '/api/threads/{threadIds}/posts/count',
        ...options
    });
};

export const getThreadPostsLatest = <ThrowOnError extends boolean = false>(options: Options<GetThreadPostsLatestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetThreadPostsLatestResponse, unknown, ThrowOnError>({
        responseTransformer: getThreadPostsLatestResponseTransformer,
        url: '/api/threads/{threadIds}/posts/latest',
        ...options
    });
};

export const createThread = <ThrowOnError extends boolean = false>(options: Options<CreateThreadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateThreadResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/threads',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const createPost = <ThrowOnError extends boolean = false>(options: Options<CreatePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreatePostResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: createPostResponseTransformer,
        url: '/api/threads/{threadId}/posts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteAvatar = <ThrowOnError extends boolean = false>(options?: Options<DeleteAvatarData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/avatars',
        ...options
    });
};

export const uploadAvatar = <ThrowOnError extends boolean = false>(options?: Options<UploadAvatarData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<unknown, UploadAvatarError, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/avatars',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUsersResponse, GetUsersError, ThrowOnError>({
        responseTransformer: getUsersResponseTransformer,
        url: '/api/users',
        ...options
    });
};

export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserByIdResponse, GetUserByIdError, ThrowOnError>({
        responseTransformer: getUserByIdResponseTransformer,
        url: '/api/users/{userId}',
        ...options
    });
};

export const getUsersByIds = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUsersByIdsResponse, unknown, ThrowOnError>({
        responseTransformer: getUsersByIdsResponseTransformer,
        url: '/api/users/batch/{userIds}',
        ...options
    });
};