// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ApiProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
  code: string;
  traceId: string;
};

export type ApiValidationError = {
  code: string;
  message: string;
  parameters: Array<string>;
};

export type ApiValidationProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
  code: string;
  errors: {
    [key: string]: ApiValidationError;
  };
  traceId: string;
};

export type ApprovedHeaderPostDeletionForbiddenError = {
  readonly $type: 'ApprovedHeaderPostDeletionForbiddenError';
};

export type AuthenticationRequiredError = {
  readonly $type: 'AuthenticationRequiredError';
};

export type CategoryDto = {
  categoryId: CategoryId;
  forumId: ForumId;
  title: CategoryTitle;
  createdBy: UserId;
  createdAt: Date;
};

export type CategoryId = string & {
  readonly __brand: 'CategoryId';
};

export type CategoryNotFoundError = {
  readonly $type: 'CategoryNotFoundError';
  categoryId: CategoryId;
};

export type CategoryTitle = string & {
  readonly __brand: 'CategoryTitle';
};

export type ClaimNotFoundError = {
  readonly $type: 'ClaimNotFoundError';
  claimName: string;
};

export type Count = number & {
  readonly __brand: 'Count';
};

export type CreateCategoryRequestBody = {
  forumId: ForumId;
  title: CategoryTitle;
};

export type CreateForumRequestBody = {
  title: ForumTitle;
};

export type CreatePostRequestBody = {
  content: PostContent;
};

export type CreateThreadRequestBody = {
  categoryId: CategoryId;
  title: ThreadTitle;
};

export type DuplicatePostBookmarkError = {
  readonly $type: 'DuplicatePostBookmarkError';
  userId: UserId;
  postId: PostId;
};

export type ForumDto = {
  forumId: ForumId;
  title: ForumTitle;
  createdBy: UserId;
  createdAt: Date;
};

export type ForumId = string & {
  readonly __brand: 'ForumId';
};

export type ForumNotFoundError = {
  readonly $type: 'ForumNotFoundError';
};

export type ForumTitle = string & {
  readonly __brand: 'ForumTitle';
};

export type GetBookmarkedPostIdsResponse = {
  postIds: Array<PostId>;
};

export enum GetBookmarkedPostsPagedQuerySortType {
  /**
   * CREATED_AT_ASC
   *
   * Sort by CreatedAt ascending
   */
  CREATED_AT_ASC = 'createdAt',
  /**
   * CREATED_AT_DESC
   *
   * Sort by CreatedAt descending
   */
  CREATED_AT_DESC = '-createdAt'
}

export enum GetCategoriesPagedQuerySortType {
  /**
   * CATEGORY_ID_ASC
   *
   * Sort by CategoryId ascending
   */
  CATEGORY_ID_ASC = 'categoryId',
  /**
   * FORUM_ID_ASC
   *
   * Sort by ForumId ascending
   */
  FORUM_ID_ASC = 'forumId',
  /**
   * CATEGORY_ID_DESC
   *
   * Sort by CategoryId descending
   */
  CATEGORY_ID_DESC = '-categoryId',
  /**
   * FORUM_ID_DESC
   *
   * Sort by ForumId descending
   */
  FORUM_ID_DESC = '-forumId'
}

export enum GetCategoryThreadsPagedQuerySortType {
  /**
   * ACTIVITY_ASC
   *
   * Sort by Activity ascending
   */
  ACTIVITY_ASC = 'activity',
  /**
   * ACTIVITY_DESC
   *
   * Sort by Activity descending
   */
  ACTIVITY_DESC = '-activity'
}

export enum GetForumsPagedQuerySortType {
  /**
   * FORUM_ID_ASC
   *
   * Sort by ForumId ascending
   */
  FORUM_ID_ASC = 'forumId',
  /**
   * FORUM_ID_DESC
   *
   * Sort by ForumId descending
   */
  FORUM_ID_DESC = '-forumId'
}

export enum GetThreadPostsPagedQuerySortType {
  /**
   * INDEX_ASC
   *
   * Sort by Index ascending
   */
  INDEX_ASC = 'index',
  /**
   * INDEX_DESC
   *
   * Sort by Index descending
   */
  INDEX_DESC = '-index'
}

export enum GetThreadsPagedQuerySortType {
  /**
   * THREAD_ID_ASC
   *
   * Sort by ThreadId ascending
   */
  THREAD_ID_ASC = 'threadId',
  /**
   * THREAD_ID_DESC
   *
   * Sort by ThreadId descending
   */
  THREAD_ID_DESC = '-threadId'
}

export type Index = number & {
  readonly __brand: 'Index';
};

export type InsufficientRoleToEditHeaderPostError = {
  readonly $type: 'InsufficientRoleToEditHeaderPostError';
};

export type InvalidPostContentError = {
  readonly $type: 'InvalidPostContentError';
};

export type InvalidSearchCursorError = {
  readonly $type: 'InvalidSearchCursorError';
};

export type InvalidSearchPaginationError = {
  readonly $type: 'InvalidSearchPaginationError';
};

export type LocaleRequiredError = {
  readonly $type: 'LocaleRequiredError';
  supportedLocales: Array<string>;
};

export type NonPostAuthorError = {
  readonly $type: 'NonPostAuthorError';
  threadId: ThreadId;
  postId: PostId;
};

export type NonThreadOwnerError = {
  readonly $type: 'NonThreadOwnerError';
};

export type NotAdminError = {
  readonly $type: 'NotAdminError';
};

export type PaginationLimitMin10Max100 = number & {
  readonly __brand: 'PaginationLimitMin10Max100';
};

export type PaginationOffset = number & {
  readonly __brand: 'PaginationOffset';
};

export type PermissionDeniedError = {
  readonly $type: 'PermissionDeniedError';
};

export type PostBookmarkNotFoundError = {
  readonly $type: 'PostBookmarkNotFoundError';
  userId: UserId;
  postId: PostId;
};

export type PostContent = string & {
  readonly __brand: 'PostContent';
};

export type PostDto = {
  postId: PostId;
  threadId: ThreadId;
  content: PostContent;
  createdBy: UserId;
  createdAt: Date;
  updatedBy: UserId;
  updatedAt: Date;
  rowVersion: RowVersion;
};

export type PostId = string & {
  readonly __brand: 'PostId';
};

export type PostLimitReachedError = {
  readonly $type: 'PostLimitReachedError';
};

export type PostNotFoundError = {
  readonly $type: 'PostNotFoundError';
};

export type PostStaleError = {
  readonly $type: 'PostStaleError';
  threadId: ThreadId;
  postId: PostId;
  rowVersion: RowVersion;
};

export type RowVersion = number & {
  readonly __brand: 'RowVersion';
};

export type SearchCursor = unknown;

export enum SearchQuerySortType {
  /**
   * RELEVANCE_ASC
   *
   * Sort by Relevance ascending
   */
  RELEVANCE_ASC = 'relevance',
  /**
   * NEWEST_ASC
   *
   * Sort by Newest ascending
   */
  NEWEST_ASC = 'newest',
  /**
   * RELEVANCE_DESC
   *
   * Sort by Relevance descending
   */
  RELEVANCE_DESC = '-relevance',
  /**
   * NEWEST_DESC
   *
   * Sort by Newest descending
   */
  NEWEST_DESC = '-newest'
}

export type SearchResultDto = {
  type: SearchResultType;
  forumTitle: ForumTitle;
  categoryId: null | CategoryId;
  categoryTitle: null | CategoryTitle;
  threadId: null | ThreadId;
  threadTitle: null | ThreadTitle;
  postId: null | PostId;
  snippet: null | string;
  forumId: ForumId;
  createdBy: UserId;
  createdAt: Date;
};

export type SearchResultsDto = {
  items: Array<SearchResultDto>;
  nextCursor: null | SearchCursor;
};

export enum SearchResultType {
  /**
   * FORUM
   */
  FORUM = 'forum',
  /**
   * CATEGORY
   */
  CATEGORY = 'category',
  /**
   * THREAD
   */
  THREAD = 'thread',
  /**
   * POST
   */
  POST = 'post'
}

export type SearchTerm = string & {
  readonly __brand: 'SearchTerm';
};

export type ThreadDto = {
  threadId: ThreadId;
  categoryId: CategoryId;
  title: ThreadTitle;
  createdBy: UserId;
  createdAt: Date;
  state: ThreadState;
  postCount: Count;
  lastHeaderPostId?: null | PostId;
};

export type ThreadId = string & {
  readonly __brand: 'ThreadId';
};

export type ThreadLockedByStateError = {
  readonly $type: 'ThreadLockedByStateError';
  state: ThreadState;
};

export type ThreadMustContainPostsError = {
  readonly $type: 'ThreadMustContainPostsError';
};

export type ThreadNotFoundError = {
  readonly $type: 'ThreadNotFoundError';
};

export type ThreadNotInStateError = {
  readonly $type: 'ThreadNotInStateError';
  state: ThreadState;
};

export enum ThreadState {
  /**
   * DRAFT
   */
  DRAFT = 'draft',
  /**
   * PENDING_APPROVAL
   */
  PENDING_APPROVAL = 'pendingApproval',
  /**
   * APPROVED
   */
  APPROVED = 'approved'
}

export type ThreadTitle = string & {
  readonly __brand: 'ThreadTitle';
};

export type UnsupportedLocaleError = {
  readonly $type: 'UnsupportedLocaleError';
  supportedLocales: Array<string>;
};

export type UpdatePostRequestBody = {
  content: PostContent;
  rowVersion: RowVersion;
};

export type UserId = string & {
  readonly __brand: 'UserId';
};

export type IFormFile = Blob | File;

export type InvalidAvatarFileSizeError = {
  readonly $type: 'InvalidAvatarFileSizeError';
  minimumFileSize: bigint;
  maximumFileSize: bigint;
  actualFileSize: bigint;
};

export type InvalidAvatarFileTypeError = {
  readonly $type: 'InvalidAvatarFileTypeError';
  expectedMediaType: string;
};

export enum ChannelType {
  /**
   * INTERNAL
   */
  INTERNAL = 'internal',
  /**
   * EMAIL
   */
  EMAIL = 'email'
}

export type CreateThreadSubscriptionRequestBody = {
  channels: Array<ChannelType>;
};

export type DuplicateThreadSubscriptionError = {
  readonly $type: 'DuplicateThreadSubscriptionError';
  userId: UserId;
  threadId: ThreadId;
};

export enum GetInternalNotificationsPagedQuerySortType {
  /**
   * OCCURRED_AT_ASC
   *
   * Sort by OccurredAt ascending
   */
  OCCURRED_AT_ASC = 'occurredAt',
  /**
   * DELIVERED_AT_ASC
   *
   * Sort by DeliveredAt ascending
   */
  DELIVERED_AT_ASC = 'deliveredAt',
  /**
   * OCCURRED_AT_DESC
   *
   * Sort by OccurredAt descending
   */
  OCCURRED_AT_DESC = '-occurredAt',
  /**
   * DELIVERED_AT_DESC
   *
   * Sort by DeliveredAt descending
   */
  DELIVERED_AT_DESC = '-deliveredAt'
}

export enum GetThreadSubscriptionLatestEventsPagedQuerySortType {
  /**
   * LATEST_EVENT_ASC
   *
   * Sort by LatestEvent ascending
   */
  LATEST_EVENT_ASC = 'latestEvent',
  /**
   * THREAD_ID_ASC
   *
   * Sort by ThreadId ascending
   */
  THREAD_ID_ASC = 'threadId',
  /**
   * LATEST_EVENT_DESC
   *
   * Sort by LatestEvent descending
   */
  LATEST_EVENT_DESC = '-latestEvent',
  /**
   * THREAD_ID_DESC
   *
   * Sort by ThreadId descending
   */
  THREAD_ID_DESC = '-threadId'
}

export enum GetThreadSubscriptionsPagedQuerySortType {
  /**
   * THREAD_ID_ASC
   *
   * Sort by ThreadId ascending
   */
  THREAD_ID_ASC = 'threadId',
  /**
   * THREAD_ID_DESC
   *
   * Sort by ThreadId descending
   */
  THREAD_ID_DESC = '-threadId'
}

export type GetThreadSubscriptionStatusQueryResult = {
  /**
   * Подписан ли пользователь на тему
   */
  isSubscribed: boolean;
};

export type InternalNotificationDto = {
  notifiableEventId: NotifiableEventId;
  payload: NotifiableEventPayload;
  occurredAt: Date;
  deliveredAt?: null | Date;
};

export type InternalNotificationsPagedDto = {
  notifications: Array<InternalNotificationDto>;
  threads: {
    [key in ThreadId]?: ThreadTitle;
  };
  users: {
    [key in UserId]?: Username;
  };
  /**
   * Общее количество уведомлений с учетом фильтрации
   */
  totalCount: Count;
};

export type NotifiableEventId = string & {
  readonly __brand: 'NotifiableEventId';
};

export type NotifiableEventPayload = ({
  $type: 'PostAdded';
} & NotifiableEventPayloadPostAddedNotifiableEventPayload) | ({
  $type: 'PostUpdated';
} & NotifiableEventPayloadPostUpdatedNotifiableEventPayload) | ({
  $type: 'ThreadApproved';
} & NotifiableEventPayloadThreadApprovedNotifiableEventPayload) | ({
  $type: 'ThreadRejected';
} & NotifiableEventPayloadThreadRejectedNotifiableEventPayload);

export type NotifiableEventPayloadPostAddedNotifiableEventPayload = {
  $type: 'PostAdded';
  threadId: ThreadId;
  postId: PostId;
  createdBy: UserId;
};

export type NotifiableEventPayloadPostUpdatedNotifiableEventPayload = {
  $type: 'PostUpdated';
  threadId: ThreadId;
  postId: PostId;
  updatedBy: UserId;
};

export type NotifiableEventPayloadThreadApprovedNotifiableEventPayload = {
  $type: 'ThreadApproved';
  threadId: ThreadId;
  createdBy: UserId;
  approvedBy: UserId;
  approvedAt: Date;
};

export type NotifiableEventPayloadThreadRejectedNotifiableEventPayload = {
  $type: 'ThreadRejected';
  threadId: ThreadId;
  createdBy: UserId;
  rejectedBy: UserId;
  rejectedAt: Date;
};

export type NotificationNotFoundError = {
  readonly $type: 'NotificationNotFoundError';
  userId: UserId;
  notifiableEventId: NotifiableEventId;
  channel: ChannelType;
};

export type PagedListOfThreadDto = {
  items: Array<ThreadDto>;
  totalCount: Count;
};

export type ThreadSubscriptionLatestEventDto = {
  notifiableEventId: NotifiableEventId;
  payload: NotifiableEventPayload;
  occurredAt: Date;
};

export type ThreadSubscriptionNotFoundError = {
  readonly $type: 'ThreadSubscriptionNotFoundError';
  userId: UserId;
  threadId: ThreadId;
};

export type Username = string & {
  readonly __brand: 'Username';
};

export type ChangeCurrentUserLocaleRequestBody = {
  locale: Locale;
};

export enum GetUsersPagedQuerySortType {
  /**
   * USER_ID_ASC
   *
   * Sort by UserId ascending
   */
  USER_ID_ASC = 'userId',
  /**
   * USER_ID_DESC
   *
   * Sort by UserId descending
   */
  USER_ID_DESC = '-userId'
}

export enum Locale {
  EN = 'en',
  RU = 'ru'
}

export type UserDto = {
  userId: UserId;
  username: Username;
  email: string;
  enabled: boolean;
  createdAt: Date;
};

export type UserNotFoundError = {
  readonly $type: 'UserNotFoundError';
};

export type CategoryNotFoundErrorWritable = {
  categoryId: CategoryId;
};

export type ClaimNotFoundErrorWritable = {
  claimName: string;
};

export type DuplicatePostBookmarkErrorWritable = {
  userId: UserId;
  postId: PostId;
};

export type LocaleRequiredErrorWritable = {
  supportedLocales: Array<string>;
};

export type NonPostAuthorErrorWritable = {
  threadId: ThreadId;
  postId: PostId;
};

export type PostBookmarkNotFoundErrorWritable = {
  userId: UserId;
  postId: PostId;
};

export type PostStaleErrorWritable = {
  threadId: ThreadId;
  postId: PostId;
  rowVersion: RowVersion;
};

export type ThreadLockedByStateErrorWritable = {
  state: ThreadState;
};

export type ThreadNotInStateErrorWritable = {
  state: ThreadState;
};

export type UnsupportedLocaleErrorWritable = {
  supportedLocales: Array<string>;
};

export type InvalidAvatarFileSizeErrorWritable = {
  minimumFileSize: bigint;
  maximumFileSize: bigint;
  actualFileSize: bigint;
};

export type InvalidAvatarFileTypeErrorWritable = {
  expectedMediaType: string;
};

export type DuplicateThreadSubscriptionErrorWritable = {
  userId: UserId;
  threadId: ThreadId;
};

export type NotificationNotFoundErrorWritable = {
  userId: UserId;
  notifiableEventId: NotifiableEventId;
  channel: ChannelType;
};

export type ThreadSubscriptionNotFoundErrorWritable = {
  userId: UserId;
  threadId: ThreadId;
};

export type GetForumsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    title?: ForumTitle;
    createdBy?: UserId;
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetForumsPagedQuerySortType;
  };
  url: '/api/forums';
};

export type GetForumsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetForumsPagedError = GetForumsPagedErrors[keyof GetForumsPagedErrors];

export type GetForumsPagedResponses = {
  /**
   * OK
   */
  200: Array<ForumDto>;
};

export type GetForumsPagedResponse = GetForumsPagedResponses[keyof GetForumsPagedResponses];

export type CreateForumData = {
  body: CreateForumRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: never;
  url: '/api/forums';
};

export type CreateForumErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: ({
    $type: 'AuthenticationRequiredError';
  } & AuthenticationRequiredError) | ({
    $type: 'ClaimNotFoundError';
  } & ClaimNotFoundError);
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type CreateForumError = CreateForumErrors[keyof CreateForumErrors];

export type CreateForumResponses = {
  /**
   * Created
   */
  201: ForumId;
};

export type CreateForumResponse = CreateForumResponses[keyof CreateForumResponses];

export type GetForumsCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    createdBy?: UserId;
  };
  url: '/api/forums/count';
};

export type GetForumsCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetForumsCountError = GetForumsCountErrors[keyof GetForumsCountErrors];

export type GetForumsCountResponses = {
  /**
   * OK
   */
  200: Count;
};

export type GetForumsCountResponse = GetForumsCountResponses[keyof GetForumsCountResponses];

export type GetForumData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    forumId: ForumId;
  };
  query?: never;
  url: '/api/forums/{forumId}';
};

export type GetForumErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: ClaimNotFoundError;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: ForumNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetForumError = GetForumErrors[keyof GetForumErrors];

export type GetForumResponses = {
  /**
   * OK
   */
  200: ForumDto;
};

export type GetForumResponse = GetForumResponses[keyof GetForumResponses];

export type GetForumsBulkData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    forumIds: Array<ForumId>;
  };
  query?: never;
  url: '/api/forums/bulk/{forumIds}';
};

export type GetForumsBulkErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetForumsBulkError = GetForumsBulkErrors[keyof GetForumsBulkErrors];

export type GetForumsBulkResponses = {
  /**
   * OK
   */
  200: {
    [key in ForumId]?: {
      value: ForumDto;
    } | {
      error: ForumNotFoundError;
    };
  };
};

export type GetForumsBulkResponse = GetForumsBulkResponses[keyof GetForumsBulkResponses];

export type GetForumsCategoriesCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    forumIds: Array<ForumId>;
  };
  query?: never;
  url: '/api/forums/{forumIds}/categories/count';
};

export type GetForumsCategoriesCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetForumsCategoriesCountError = GetForumsCategoriesCountErrors[keyof GetForumsCategoriesCountErrors];

export type GetForumsCategoriesCountResponses = {
  /**
   * OK
   */
  200: {
    [key in ForumId]?: {
      value: Count;
    } | {
      error: ForumNotFoundError;
    };
  };
};

export type GetForumsCategoriesCountResponse = GetForumsCategoriesCountResponses[keyof GetForumsCategoriesCountResponses];

export type GetCategoriesPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    forumIds?: Array<ForumId>;
    title?: CategoryTitle;
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: Array<GetCategoriesPagedQuerySortType>;
  };
  url: '/api/categories';
};

export type GetCategoriesPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoriesPagedError = GetCategoriesPagedErrors[keyof GetCategoriesPagedErrors];

export type GetCategoriesPagedResponses = {
  /**
   * OK
   */
  200: Array<CategoryDto>;
};

export type GetCategoriesPagedResponse = GetCategoriesPagedResponses[keyof GetCategoriesPagedResponses];

export type CreateCategoryData = {
  body: CreateCategoryRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: never;
  url: '/api/categories';
};

export type CreateCategoryErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: ({
    $type: 'AuthenticationRequiredError';
  } & AuthenticationRequiredError) | ({
    $type: 'ClaimNotFoundError';
  } & ClaimNotFoundError);
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: ForumNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
  /**
   * Created
   */
  201: CategoryId;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type GetCategoryData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    categoryId: CategoryId;
  };
  query?: never;
  url: '/api/categories/{categoryId}';
};

export type GetCategoryErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: CategoryNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
  /**
   * OK
   */
  200: CategoryDto;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type GetCategoriesBulkData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    categoryIds: Array<CategoryId>;
  };
  query?: never;
  url: '/api/categories/bulk/{categoryIds}';
};

export type GetCategoriesBulkErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoriesBulkError = GetCategoriesBulkErrors[keyof GetCategoriesBulkErrors];

export type GetCategoriesBulkResponses = {
  /**
   * OK
   */
  200: {
    [key in CategoryId]?: {
      value: CategoryDto;
    } | {
      error: CategoryNotFoundError;
    };
  };
};

export type GetCategoriesBulkResponse = GetCategoriesBulkResponses[keyof GetCategoriesBulkResponses];

export type GetCategoriesPostsCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    categoryIds: Array<CategoryId>;
  };
  query?: never;
  url: '/api/categories/{categoryIds}/posts/count';
};

export type GetCategoriesPostsCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoriesPostsCountError = GetCategoriesPostsCountErrors[keyof GetCategoriesPostsCountErrors];

export type GetCategoriesPostsCountResponses = {
  /**
   * OK
   */
  200: {
    [key in CategoryId]?: {
      value: Count;
    } | {
      error: CategoryNotFoundError;
    };
  };
};

export type GetCategoriesPostsCountResponse = GetCategoriesPostsCountResponses[keyof GetCategoriesPostsCountResponses];

export type GetCategoriesPostsLatestData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    categoryIds: Array<CategoryId>;
  };
  query?: never;
  url: '/api/categories/{categoryIds}/posts/latest';
};

export type GetCategoriesPostsLatestErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoriesPostsLatestError = GetCategoriesPostsLatestErrors[keyof GetCategoriesPostsLatestErrors];

export type GetCategoriesPostsLatestResponses = {
  /**
   * OK
   */
  200: {
    [key in CategoryId]?: PostDto;
  };
};

export type GetCategoriesPostsLatestResponse = GetCategoriesPostsLatestResponses[keyof GetCategoriesPostsLatestResponses];

export type GetCategoriesThreadsCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    categoryIds: Array<CategoryId>;
  };
  query?: {
    state?: ThreadState;
  };
  url: '/api/categories/{categoryIds}/threads/count';
};

export type GetCategoriesThreadsCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoriesThreadsCountError = GetCategoriesThreadsCountErrors[keyof GetCategoriesThreadsCountErrors];

export type GetCategoriesThreadsCountResponses = {
  /**
   * OK
   */
  200: {
    [key in CategoryId]?: {
      value: Count;
    } | {
      error: CategoryNotFoundError;
    };
  };
};

export type GetCategoriesThreadsCountResponse = GetCategoriesThreadsCountResponses[keyof GetCategoriesThreadsCountResponses];

export type GetCategoryThreadsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    categoryId: CategoryId;
  };
  query?: {
    state?: ThreadState;
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetCategoryThreadsPagedQuerySortType;
  };
  url: '/api/categories/{categoryId}/threads';
};

export type GetCategoryThreadsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: CategoryNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetCategoryThreadsPagedError = GetCategoryThreadsPagedErrors[keyof GetCategoryThreadsPagedErrors];

export type GetCategoryThreadsPagedResponses = {
  /**
   * OK
   */
  200: Array<ThreadDto>;
};

export type GetCategoryThreadsPagedResponse = GetCategoryThreadsPagedResponses[keyof GetCategoryThreadsPagedResponses];

export type GetThreadsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    createdBy?: UserId;
    status?: ThreadState;
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetThreadsPagedQuerySortType;
  };
  url: '/api/threads';
};

export type GetThreadsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadsPagedError = GetThreadsPagedErrors[keyof GetThreadsPagedErrors];

export type GetThreadsPagedResponses = {
  /**
   * OK
   */
  200: Array<ThreadDto>;
};

export type GetThreadsPagedResponse = GetThreadsPagedResponses[keyof GetThreadsPagedResponses];

export type CreateThreadData = {
  body: CreateThreadRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: never;
  url: '/api/threads';
};

export type CreateThreadErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: CategoryNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type CreateThreadError = CreateThreadErrors[keyof CreateThreadErrors];

export type CreateThreadResponses = {
  /**
   * Created
   */
  201: ThreadId;
};

export type CreateThreadResponse = CreateThreadResponses[keyof CreateThreadResponses];

export type GetThreadsCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    createdBy?: UserId;
    status?: ThreadState;
  };
  url: '/api/threads/count';
};

export type GetThreadsCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadsCountError = GetThreadsCountErrors[keyof GetThreadsCountErrors];

export type GetThreadsCountResponses = {
  /**
   * OK
   */
  200: Count;
};

export type GetThreadsCountResponse = GetThreadsCountResponses[keyof GetThreadsCountResponses];

export type GetThreadData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/threads/{threadId}';
};

export type GetThreadErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ({
    $type: 'PermissionDeniedError';
  } & PermissionDeniedError) | ({
    $type: 'NonThreadOwnerError';
  } & NonThreadOwnerError);
  /**
   * Not Found
   */
  404: ThreadNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadError = GetThreadErrors[keyof GetThreadErrors];

export type GetThreadResponses = {
  /**
   * OK
   */
  200: ThreadDto;
};

export type GetThreadResponse = GetThreadResponses[keyof GetThreadResponses];

export type GetThreadsBulkData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadIds: Array<ThreadId>;
  };
  query?: never;
  url: '/api/threads/bulk/{threadIds}';
};

export type GetThreadsBulkErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadsBulkError = GetThreadsBulkErrors[keyof GetThreadsBulkErrors];

export type GetThreadsBulkResponses = {
  /**
   * OK
   */
  200: {
    [key in ThreadId]?: {
      value: ThreadDto;
    } | {
      error: ({
        $type: 'ThreadNotFoundError';
      } & ThreadNotFoundError) | ({
        $type: 'PermissionDeniedError';
      } & PermissionDeniedError);
    };
  };
};

export type GetThreadsBulkResponse = GetThreadsBulkResponses[keyof GetThreadsBulkResponses];

export type GetThreadPostsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadId: ThreadId;
  };
  query?: {
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetThreadPostsPagedQuerySortType;
  };
  url: '/api/threads/{threadId}/posts';
};

export type GetThreadPostsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: ThreadNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadPostsPagedError = GetThreadPostsPagedErrors[keyof GetThreadPostsPagedErrors];

export type GetThreadPostsPagedResponses = {
  /**
   * OK
   */
  200: Array<PostDto>;
};

export type GetThreadPostsPagedResponse = GetThreadPostsPagedResponses[keyof GetThreadPostsPagedResponses];

export type CreatePostData = {
  body: CreatePostRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/threads/{threadId}/posts';
};

export type CreatePostErrors = {
  /**
   * Bad Request
   */
  400: InvalidPostContentError;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NonThreadOwnerError;
  /**
   * Not Found
   */
  404: ThreadNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: ({
    $type: 'ThreadLockedByStateError';
  } & ThreadLockedByStateError) | ({
    $type: 'PostLimitReachedError';
  } & PostLimitReachedError);
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
  /**
   * Created
   */
  201: PostId;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type GetThreadsPostsCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadIds: Array<ThreadId>;
  };
  query?: {
    status?: ThreadState;
  };
  url: '/api/threads/{threadIds}/posts/count';
};

export type GetThreadsPostsCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadsPostsCountError = GetThreadsPostsCountErrors[keyof GetThreadsPostsCountErrors];

export type GetThreadsPostsCountResponses = {
  /**
   * OK
   */
  200: {
    [key in ThreadId]?: {
      value: Count;
    } | {
      error: ({
        $type: 'ThreadNotFoundError';
      } & ThreadNotFoundError) | ({
        $type: 'PermissionDeniedError';
      } & PermissionDeniedError);
    };
  };
};

export type GetThreadsPostsCountResponse = GetThreadsPostsCountResponses[keyof GetThreadsPostsCountResponses];

export type GetThreadsPostsLatestData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadIds: Array<ThreadId>;
  };
  query?: never;
  url: '/api/threads/{threadIds}/posts/latest';
};

export type GetThreadsPostsLatestErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadsPostsLatestError = GetThreadsPostsLatestErrors[keyof GetThreadsPostsLatestErrors];

export type GetThreadsPostsLatestResponses = {
  /**
   * OK
   */
  200: {
    [key in ThreadId]?: {
      value: PostDto;
    } | {
      error: ({
        $type: 'ThreadNotFoundError';
      } & ThreadNotFoundError) | ({
        $type: 'PermissionDeniedError';
      } & PermissionDeniedError) | ({
        $type: 'PostNotFoundError';
      } & PostNotFoundError);
    };
  };
};

export type GetThreadsPostsLatestResponse = GetThreadsPostsLatestResponses[keyof GetThreadsPostsLatestResponses];

export type RequestThreadApprovalData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/threads/{threadId}/request-approval';
};

export type RequestThreadApprovalErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NonThreadOwnerError;
  /**
   * Not Found
   */
  404: ThreadNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: ({
    $type: 'ThreadNotInStateError';
  } & ThreadNotInStateError) | ({
    $type: 'ThreadMustContainPostsError';
  } & ThreadMustContainPostsError);
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type RequestThreadApprovalError = RequestThreadApprovalErrors[keyof RequestThreadApprovalErrors];

export type RequestThreadApprovalResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RequestThreadApprovalResponse = RequestThreadApprovalResponses[keyof RequestThreadApprovalResponses];

export type ApproveThreadData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/threads/{threadId}/approve';
};

export type ApproveThreadErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: ThreadNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: ThreadNotInStateError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type ApproveThreadError = ApproveThreadErrors[keyof ApproveThreadErrors];

export type ApproveThreadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type ApproveThreadResponse = ApproveThreadResponses[keyof ApproveThreadResponses];

export type RejectThreadData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/threads/{threadId}/reject';
};

export type RejectThreadErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: ThreadNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: ThreadNotInStateError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type RejectThreadError = RejectThreadErrors[keyof RejectThreadErrors];

export type RejectThreadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RejectThreadResponse = RejectThreadResponses[keyof RejectThreadResponses];

export type DeletePostData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postId: PostId;
  };
  query?: never;
  url: '/api/posts/{postId}';
};

export type DeletePostErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ({
    $type: 'NonPostAuthorError';
  } & NonPostAuthorError) | ({
    $type: 'ApprovedHeaderPostDeletionForbiddenError';
  } & ApprovedHeaderPostDeletionForbiddenError);
  /**
   * Not Found
   */
  404: ({
    $type: 'PostNotFoundError';
  } & PostNotFoundError) | ({
    $type: 'ThreadNotFoundError';
  } & ThreadNotFoundError);
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: ThreadLockedByStateError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type DeletePostError = DeletePostErrors[keyof DeletePostErrors];

export type DeletePostResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePostResponse = DeletePostResponses[keyof DeletePostResponses];

export type GetPostData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postId: PostId;
  };
  query?: never;
  url: '/api/posts/{postId}';
};

export type GetPostErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: PostNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetPostError = GetPostErrors[keyof GetPostErrors];

export type GetPostResponses = {
  /**
   * OK
   */
  200: PostDto;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type UpdatePostData = {
  body: UpdatePostRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postId: PostId;
  };
  query?: never;
  url: '/api/posts/{postId}';
};

export type UpdatePostErrors = {
  /**
   * Bad Request
   */
  400: InvalidPostContentError;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: ({
    $type: 'NonPostAuthorError';
  } & NonPostAuthorError) | ({
    $type: 'InsufficientRoleToEditHeaderPostError';
  } & InsufficientRoleToEditHeaderPostError);
  /**
   * Not Found
   */
  404: ({
    $type: 'PostNotFoundError';
  } & PostNotFoundError) | ({
    $type: 'ThreadNotFoundError';
  } & ThreadNotFoundError);
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: ({
    $type: 'ThreadLockedByStateError';
  } & ThreadLockedByStateError) | ({
    $type: 'PostStaleError';
  } & PostStaleError);
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type GetPostIndexData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postId: PostId;
  };
  query?: never;
  url: '/api/posts/{postId}/order';
};

export type GetPostIndexErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: PostNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetPostIndexError = GetPostIndexErrors[keyof GetPostIndexErrors];

export type GetPostIndexResponses = {
  /**
   * OK
   */
  200: Index;
};

export type GetPostIndexResponse = GetPostIndexResponses[keyof GetPostIndexResponses];

export type GetBookmarkedPostIdsData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postIds: Array<PostId>;
  };
  query?: never;
  url: '/api/posts/bookmarks/bulk/{postIds}';
};

export type GetBookmarkedPostIdsErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetBookmarkedPostIdsError = GetBookmarkedPostIdsErrors[keyof GetBookmarkedPostIdsErrors];

export type GetBookmarkedPostIdsResponses = {
  /**
   * OK
   */
  200: GetBookmarkedPostIdsResponse;
};

export type GetBookmarkedPostIdsResponse2 = GetBookmarkedPostIdsResponses[keyof GetBookmarkedPostIdsResponses];

export type DeletePostBookmarkData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postId: PostId;
  };
  query?: never;
  url: '/api/posts/bookmarks/{postId}';
};

export type DeletePostBookmarkErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: PostBookmarkNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type DeletePostBookmarkError = DeletePostBookmarkErrors[keyof DeletePostBookmarkErrors];

export type DeletePostBookmarkResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeletePostBookmarkResponse = DeletePostBookmarkResponses[keyof DeletePostBookmarkResponses];

export type CreatePostBookmarkData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    postId: PostId;
  };
  query?: never;
  url: '/api/posts/bookmarks/{postId}';
};

export type CreatePostBookmarkErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: PermissionDeniedError;
  /**
   * Not Found
   */
  404: PostNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: DuplicatePostBookmarkError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type CreatePostBookmarkError = CreatePostBookmarkErrors[keyof CreatePostBookmarkErrors];

export type CreatePostBookmarkResponses = {
  /**
   * No Content
   */
  204: void;
};

export type CreatePostBookmarkResponse = CreatePostBookmarkResponses[keyof CreatePostBookmarkResponses];

export type GetBookmarkedPostsCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
  };
  query?: never;
  url: '/api/users/{userId}/bookmarks/count';
};

export type GetBookmarkedPostsCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetBookmarkedPostsCountError = GetBookmarkedPostsCountErrors[keyof GetBookmarkedPostsCountErrors];

export type GetBookmarkedPostsCountResponses = {
  /**
   * OK
   */
  200: Count;
};

export type GetBookmarkedPostsCountResponse = GetBookmarkedPostsCountResponses[keyof GetBookmarkedPostsCountResponses];

export type GetBookmarkedPostsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
  };
  query?: {
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetBookmarkedPostsPagedQuerySortType;
  };
  url: '/api/users/{userId}/bookmarks';
};

export type GetBookmarkedPostsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetBookmarkedPostsPagedError = GetBookmarkedPostsPagedErrors[keyof GetBookmarkedPostsPagedErrors];

export type GetBookmarkedPostsPagedResponses = {
  /**
   * OK
   */
  200: Array<PostDto>;
};

export type GetBookmarkedPostsPagedResponse = GetBookmarkedPostsPagedResponses[keyof GetBookmarkedPostsPagedResponses];

export type SearchData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query: {
    term: SearchTerm;
    type?: SearchResultType;
    offset?: PaginationOffset;
    sort?: SearchQuerySortType;
    limit?: PaginationLimitMin10Max100;
    cursor?: SearchCursor;
  };
  url: '/api/search';
};

export type SearchErrors = {
  /**
   * Bad Request
   */
  400: ({
    $type: 'InvalidSearchCursorError';
  } & InvalidSearchCursorError) | ({
    $type: 'InvalidSearchPaginationError';
  } & InvalidSearchPaginationError);
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
  /**
   * OK
   */
  200: SearchResultsDto;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type DeleteAvatarData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: never;
  url: '/api/avatars';
};

export type DeleteAvatarErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type DeleteAvatarError = DeleteAvatarErrors[keyof DeleteAvatarErrors];

export type DeleteAvatarResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAvatarResponse = DeleteAvatarResponses[keyof DeleteAvatarResponses];

export type UploadAvatarData = {
  body: {
    file: IFormFile;
  };
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: never;
  url: '/api/avatars';
};

export type UploadAvatarErrors = {
  /**
   * Bad Request
   */
  400: ({
    $type: 'InvalidAvatarFileSizeError';
  } & InvalidAvatarFileSizeError) | ({
    $type: 'InvalidAvatarFileTypeError';
  } & InvalidAvatarFileTypeError);
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type UploadAvatarError = UploadAvatarErrors[keyof UploadAvatarErrors];

export type UploadAvatarResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UploadAvatarResponse = UploadAvatarResponses[keyof UploadAvatarResponses];

export type GetInternalNotificationCountData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    isDelivered?: boolean;
  };
  url: '/api/me/notifications/count';
};

export type GetInternalNotificationCountErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetInternalNotificationCountError = GetInternalNotificationCountErrors[keyof GetInternalNotificationCountErrors];

export type GetInternalNotificationCountResponses = {
  /**
   * OK
   */
  200: Count;
};

export type GetInternalNotificationCountResponse = GetInternalNotificationCountResponses[keyof GetInternalNotificationCountResponses];

export type GetInternalNotificationsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    isDelivered?: boolean;
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: Array<GetInternalNotificationsPagedQuerySortType>;
  };
  url: '/api/me/notifications';
};

export type GetInternalNotificationsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetInternalNotificationsPagedError = GetInternalNotificationsPagedErrors[keyof GetInternalNotificationsPagedErrors];

export type GetInternalNotificationsPagedResponses = {
  /**
   * OK
   */
  200: InternalNotificationsPagedDto;
};

export type GetInternalNotificationsPagedResponse = GetInternalNotificationsPagedResponses[keyof GetInternalNotificationsPagedResponses];

export type MarkInternalNotificationAsReadData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    notifiableEventId: NotifiableEventId;
  };
  query?: never;
  url: '/api/me/notifications/{notifiableEventId}/mark-read';
};

export type MarkInternalNotificationAsReadErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: NotificationNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type MarkInternalNotificationAsReadError = MarkInternalNotificationAsReadErrors[keyof MarkInternalNotificationAsReadErrors];

export type MarkInternalNotificationAsReadResponses = {
  /**
   * No Content
   */
  204: void;
};

export type MarkInternalNotificationAsReadResponse = MarkInternalNotificationAsReadResponses[keyof MarkInternalNotificationAsReadResponses];

export type DeleteInternalNotificationData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    notifiableEventId: NotifiableEventId;
  };
  query?: never;
  url: '/api/me/notifications/{notifiableEventId}';
};

export type DeleteInternalNotificationErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: NotificationNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type DeleteInternalNotificationError = DeleteInternalNotificationErrors[keyof DeleteInternalNotificationErrors];

export type DeleteInternalNotificationResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteInternalNotificationResponse = DeleteInternalNotificationResponses[keyof DeleteInternalNotificationResponses];

export type GetThreadSubscriptionsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
  };
  query?: {
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetThreadSubscriptionsPagedQuerySortType;
  };
  url: '/api/users/{userId}/subscriptions';
};

export type GetThreadSubscriptionsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadSubscriptionsPagedError = GetThreadSubscriptionsPagedErrors[keyof GetThreadSubscriptionsPagedErrors];

export type GetThreadSubscriptionsPagedResponses = {
  /**
   * OK
   */
  200: PagedListOfThreadDto;
};

export type GetThreadSubscriptionsPagedResponse = GetThreadSubscriptionsPagedResponses[keyof GetThreadSubscriptionsPagedResponses];

export type GetThreadSubscriptionLatestEventsPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
  };
  query?: {
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetThreadSubscriptionLatestEventsPagedQuerySortType;
  };
  url: '/api/users/{userId}/subscriptions/latest-events';
};

export type GetThreadSubscriptionLatestEventsPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadSubscriptionLatestEventsPagedError = GetThreadSubscriptionLatestEventsPagedErrors[keyof GetThreadSubscriptionLatestEventsPagedErrors];

export type GetThreadSubscriptionLatestEventsPagedResponses = {
  /**
   * OK
   */
  200: Array<ThreadSubscriptionLatestEventDto>;
};

export type GetThreadSubscriptionLatestEventsPagedResponse = GetThreadSubscriptionLatestEventsPagedResponses[keyof GetThreadSubscriptionLatestEventsPagedResponses];

export type GetThreadSubscriptionStatusData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/users/{userId}/subscriptions/{threadId}/status';
};

export type GetThreadSubscriptionStatusErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetThreadSubscriptionStatusError = GetThreadSubscriptionStatusErrors[keyof GetThreadSubscriptionStatusErrors];

export type GetThreadSubscriptionStatusResponses = {
  /**
   * OK
   */
  200: GetThreadSubscriptionStatusQueryResult;
};

export type GetThreadSubscriptionStatusResponse = GetThreadSubscriptionStatusResponses[keyof GetThreadSubscriptionStatusResponses];

export type DeleteThreadSubscriptionData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/users/{userId}/subscriptions/{threadId}';
};

export type DeleteThreadSubscriptionErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * Not Found
   */
  404: ThreadSubscriptionNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type DeleteThreadSubscriptionError = DeleteThreadSubscriptionErrors[keyof DeleteThreadSubscriptionErrors];

export type DeleteThreadSubscriptionResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteThreadSubscriptionResponse = DeleteThreadSubscriptionResponses[keyof DeleteThreadSubscriptionResponses];

export type CreateThreadSubscriptionData = {
  body: CreateThreadSubscriptionRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
    threadId: ThreadId;
  };
  query?: never;
  url: '/api/users/{userId}/subscriptions/{threadId}';
};

export type CreateThreadSubscriptionErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: NotAdminError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Conflict
   */
  409: DuplicateThreadSubscriptionError;
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type CreateThreadSubscriptionError = CreateThreadSubscriptionErrors[keyof CreateThreadSubscriptionErrors];

export type CreateThreadSubscriptionResponses = {
  /**
   * No Content
   */
  204: void;
};

export type CreateThreadSubscriptionResponse = CreateThreadSubscriptionResponses[keyof CreateThreadSubscriptionResponses];

export type ChangeCurrentUserLocaleData = {
  body: ChangeCurrentUserLocaleRequestBody;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: never;
  url: '/api/users/current/locale';
};

export type ChangeCurrentUserLocaleErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Not Found
   */
  404: UserNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Request payload is too large
   */
  413: ApiProblemDetails;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type ChangeCurrentUserLocaleError = ChangeCurrentUserLocaleErrors[keyof ChangeCurrentUserLocaleErrors];

export type ChangeCurrentUserLocaleResponses = {
  /**
   * No Content
   */
  204: void;
};

export type ChangeCurrentUserLocaleResponse = ChangeCurrentUserLocaleResponses[keyof ChangeCurrentUserLocaleResponses];

export type GetUsersPagedData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path?: never;
  query?: {
    offset?: PaginationOffset;
    limit?: PaginationLimitMin10Max100;
    sort?: GetUsersPagedQuerySortType;
  };
  url: '/api/users';
};

export type GetUsersPagedErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetUsersPagedError = GetUsersPagedErrors[keyof GetUsersPagedErrors];

export type GetUsersPagedResponses = {
  /**
   * OK
   */
  200: Array<UserDto>;
};

export type GetUsersPagedResponse = GetUsersPagedResponses[keyof GetUsersPagedResponses];

export type GetUserData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userId: UserId;
  };
  query?: never;
  url: '/api/users/{userId}';
};

export type GetUserErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * Not Found
   */
  404: UserNotFoundError;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * OK
   */
  200: UserDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUsersBulkData = {
  body?: never;
  headers: {
    /**
     * Requested response locale.
     */
    'Accept-Language': 'en' | 'ru';
  };
  path: {
    userIds: Array<UserId>;
  };
  query?: never;
  url: '/api/users/bulk/{userIds}';
};

export type GetUsersBulkErrors = {
  /**
   * Invalid request
   */
  400: ApiProblemDetails | ApiValidationProblemDetails;
  /**
   * A supported Accept-Language header is required
   */
  406: LocaleRequiredError | UnsupportedLocaleError;
  /**
   * Unexpected server error
   */
  500: ApiProblemDetails;
};

export type GetUsersBulkError = GetUsersBulkErrors[keyof GetUsersBulkErrors];

export type GetUsersBulkResponses = {
  /**
   * OK
   */
  200: {
    [key in UserId]?: {
      value: UserDto;
    } | {
      error: UserNotFoundError;
    };
  };
};

export type GetUsersBulkResponse = GetUsersBulkResponses[keyof GetUsersBulkResponses];
