// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vApiProblemDetails = v.object({
  type: v.nullish(v.string()),
  title: v.nullish(v.string()),
  status: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
  detail: v.nullish(v.string()),
  instance: v.nullish(v.string()),
  code: v.string(),
  traceId: v.string()
});

export const vApiValidationError = v.object({
  code: v.string(),
  message: v.string(),
  parameters: v.array(v.string())
});

export const vApiValidationProblemDetails = v.object({
  type: v.nullish(v.string()),
  title: v.nullish(v.string()),
  status: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
  detail: v.nullish(v.string()),
  instance: v.nullish(v.string()),
  code: v.string(),
  errors: v.record(v.string(), vApiValidationError),
  traceId: v.string()
});

export const vApprovedHeaderPostDeletionForbiddenError = v.object({
  $type: v.pipe(v.literal('ApprovedHeaderPostDeletionForbiddenError'), v.readonly())
});

export const vAuthenticationRequiredError = v.object({
  $type: v.pipe(v.literal('AuthenticationRequiredError'), v.readonly())
});

export const vCategoryId = v.pipe(v.string(), v.uuid(), v.regex(/^(?!00000000-0000-0000-0000-000000000000$)/));

export const vCategoryNotFoundError = v.object({
  $type: v.pipe(v.literal('CategoryNotFoundError'), v.readonly()),
  categoryId: vCategoryId
});

export const vCategoryTitle = v.pipe(v.string(), v.minLength(3), v.maxLength(128), v.regex(/^(?!\s*$).+/));

export const vClaimNotFoundError = v.object({
  $type: v.pipe(v.literal('ClaimNotFoundError'), v.readonly()),
  claimName: v.string()
});

export const vCount = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647));

export const vForumId = v.pipe(v.string(), v.uuid(), v.regex(/^(?!00000000-0000-0000-0000-000000000000$)/));

export const vCreateCategoryRequestBody = v.object({
  forumId: vForumId,
  title: vCategoryTitle
});

export const vForumNotFoundError = v.object({
  $type: v.pipe(v.literal('ForumNotFoundError'), v.readonly())
});

export const vForumTitle = v.pipe(v.string(), v.minLength(3), v.maxLength(64), v.regex(/^(?!\s*$).+/));

export const vCreateForumRequestBody = v.object({
  title: vForumTitle
});

export const vGetBookmarkedPostsPagedQuerySortType = v.optional(v.picklist(['createdAt', '-createdAt']), '-createdAt');

export const vGetCategoriesPagedQuerySortType = v.picklist([
  'categoryId',
  'forumId',
  '-categoryId',
  '-forumId'
]);

export const vGetCategoryThreadsPagedQuerySortType = v.optional(v.picklist(['activity', '-activity']), 'activity');

export const vGetForumsPagedQuerySortType = v.optional(v.picklist(['forumId', '-forumId']), 'forumId');

export const vGetThreadPostsPagedQuerySortType = v.optional(v.picklist(['index', '-index']), 'index');

export const vGetThreadsPagedQuerySortType = v.optional(v.picklist(['threadId', '-threadId']), 'threadId');

export const vIndex = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647));

export const vInsufficientRoleToEditHeaderPostError = v.object({
  $type: v.pipe(v.literal('InsufficientRoleToEditHeaderPostError'), v.readonly())
});

export const vInvalidPostContentError = v.object({
  $type: v.pipe(v.literal('InvalidPostContentError'), v.readonly())
});

export const vInvalidSearchCursorError = v.object({
  $type: v.pipe(v.literal('InvalidSearchCursorError'), v.readonly())
});

export const vInvalidSearchPaginationError = v.object({
  $type: v.pipe(v.literal('InvalidSearchPaginationError'), v.readonly())
});

export const vLocaleRequiredError = v.object({
  $type: v.pipe(v.literal('LocaleRequiredError'), v.readonly()),
  supportedLocales: v.array(v.string())
});

export const vNonThreadOwnerError = v.object({
  $type: v.pipe(v.literal('NonThreadOwnerError'), v.readonly())
});

export const vNotAdminError = v.object({
  $type: v.pipe(v.literal('NotAdminError'), v.readonly())
});

export const vPaginationLimitMin10Max100 = v.optional(v.pipe(v.number(), v.integer(), v.minValue(10), v.maxValue(100)), 100);

export const vPaginationOffset = v.optional(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647)), 0);

export const vPermissionDeniedError = v.object({
  $type: v.pipe(v.literal('PermissionDeniedError'), v.readonly())
});

export const vPostContent = v.pipe(v.string(), v.minLength(2), v.maxLength(1024), v.regex(/^(?!\s*$).+/));

export const vCreatePostRequestBody = v.object({
  content: vPostContent
});

export const vPostId = v.pipe(v.string(), v.uuid(), v.regex(/^(?!00000000-0000-0000-0000-000000000000$)/));

export const vGetBookmarkedPostIdsResponse = v.object({
  postIds: v.array(vPostId)
});

export const vPostLimitReachedError = v.object({
  $type: v.pipe(v.literal('PostLimitReachedError'), v.readonly())
});

export const vPostNotFoundError = v.object({
  $type: v.pipe(v.literal('PostNotFoundError'), v.readonly())
});

export const vRowVersion = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(4294967295));

export const vSearchCursor = v.unknown();

export const vSearchQuerySortType = v.optional(v.picklist([
  'relevance',
  'newest',
  '-relevance',
  '-newest'
]), '-relevance');

export const vSearchResultType = v.picklist([
  'forum',
  'category',
  'thread',
  'post'
]);

export const vSearchTerm = v.pipe(v.string(), v.minLength(2), v.maxLength(100), v.regex(/^(?!\s*$).+/));

export const vThreadId = v.pipe(v.string(), v.uuid(), v.regex(/^(?!00000000-0000-0000-0000-000000000000$)/));

export const vNonPostAuthorError = v.object({
  $type: v.pipe(v.literal('NonPostAuthorError'), v.readonly()),
  threadId: vThreadId,
  postId: vPostId
});

export const vPostStaleError = v.object({
  $type: v.pipe(v.literal('PostStaleError'), v.readonly()),
  threadId: vThreadId,
  postId: vPostId,
  rowVersion: vRowVersion
});

export const vThreadMustContainPostsError = v.object({
  $type: v.pipe(v.literal('ThreadMustContainPostsError'), v.readonly())
});

export const vThreadNotFoundError = v.object({
  $type: v.pipe(v.literal('ThreadNotFoundError'), v.readonly())
});

export const vThreadState = v.picklist([
  'draft',
  'pendingApproval',
  'approved'
]);

export const vThreadLockedByStateError = v.object({
  $type: v.pipe(v.literal('ThreadLockedByStateError'), v.readonly()),
  state: vThreadState
});

export const vThreadNotInStateError = v.object({
  $type: v.pipe(v.literal('ThreadNotInStateError'), v.readonly()),
  state: vThreadState
});

export const vThreadTitle = v.pipe(v.string(), v.minLength(3), v.maxLength(128), v.regex(/^(?!\s*$).+/));

export const vCreateThreadRequestBody = v.object({
  categoryId: vCategoryId,
  title: vThreadTitle
});

export const vUnsupportedLocaleError = v.object({
  $type: v.pipe(v.literal('UnsupportedLocaleError'), v.readonly()),
  supportedLocales: v.array(v.string())
});

export const vUpdatePostRequestBody = v.object({
  content: vPostContent,
  rowVersion: vRowVersion
});

export const vUserId = v.pipe(v.string(), v.uuid(), v.regex(/^(?!00000000-0000-0000-0000-000000000000$)/));

export const vCategoryDto = v.object({
  categoryId: vCategoryId,
  forumId: vForumId,
  title: vCategoryTitle,
  createdBy: vUserId,
  createdAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vDuplicatePostBookmarkError = v.object({
  $type: v.pipe(v.literal('DuplicatePostBookmarkError'), v.readonly()),
  userId: vUserId,
  postId: vPostId
});

export const vForumDto = v.object({
  forumId: vForumId,
  title: vForumTitle,
  createdBy: vUserId,
  createdAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vPostBookmarkNotFoundError = v.object({
  $type: v.pipe(v.literal('PostBookmarkNotFoundError'), v.readonly()),
  userId: vUserId,
  postId: vPostId
});

export const vPostDto = v.object({
  postId: vPostId,
  threadId: vThreadId,
  content: vPostContent,
  createdBy: vUserId,
  createdAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value))),
  updatedBy: vUserId,
  updatedAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value))),
  rowVersion: vRowVersion
});

export const vSearchResultDto = v.object({
  type: vSearchResultType,
  forumTitle: vForumTitle,
  categoryId: v.nullable(vCategoryId),
  categoryTitle: v.nullable(vCategoryTitle),
  threadId: v.nullable(vThreadId),
  threadTitle: v.nullable(vThreadTitle),
  postId: v.nullable(vPostId),
  snippet: v.nullable(v.string()),
  forumId: vForumId,
  createdBy: vUserId,
  createdAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vSearchResultsDto = v.object({
  items: v.array(vSearchResultDto),
  nextCursor: v.nullable(vSearchCursor)
});

export const vThreadDto = v.object({
  threadId: vThreadId,
  categoryId: vCategoryId,
  title: vThreadTitle,
  createdBy: vUserId,
  createdAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value))),
  state: vThreadState,
  postCount: vCount,
  lastHeaderPostId: v.nullish(vPostId)
});

export const vIFormFile = v.string();

export const vInvalidAvatarFileSizeError = v.object({
  $type: v.pipe(v.literal('InvalidAvatarFileSizeError'), v.readonly()),
  minimumFileSize: v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
  ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
  maximumFileSize: v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
  ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
  actualFileSize: v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
  ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vInvalidAvatarFileTypeError = v.object({
  $type: v.pipe(v.literal('InvalidAvatarFileTypeError'), v.readonly()),
  expectedMediaType: v.string()
});

export const vChannelType = v.picklist(['internal', 'email']);

export const vCreateThreadSubscriptionRequestBody = v.object({
  channels: v.pipe(v.array(vChannelType), v.minLength(1))
});

export const vDuplicateThreadSubscriptionError = v.object({
  $type: v.pipe(v.literal('DuplicateThreadSubscriptionError'), v.readonly()),
  userId: vUserId,
  threadId: vThreadId
});

export const vGetInternalNotificationsPagedQuerySortType = v.picklist([
  'occurredAt',
  'deliveredAt',
  '-occurredAt',
  '-deliveredAt'
]);

export const vGetThreadSubscriptionLatestEventsPagedQuerySortType = v.optional(v.picklist([
  'latestEvent',
  'threadId',
  '-latestEvent',
  '-threadId'
]), '-latestEvent');

export const vGetThreadSubscriptionsPagedQuerySortType = v.optional(v.picklist(['threadId', '-threadId']), 'threadId');

export const vGetThreadSubscriptionStatusQueryResult = v.object({
  isSubscribed: v.boolean()
});

export const vNotifiableEventId = v.pipe(v.string(), v.uuid(), v.regex(/^(?!00000000-0000-0000-0000-000000000000$)/));

export const vNotifiableEventPayloadPostAddedNotifiableEventPayload = v.object({
  $type: v.picklist(['PostAdded']),
  threadId: vThreadId,
  postId: vPostId,
  createdBy: vUserId
});

export const vNotifiableEventPayloadPostUpdatedNotifiableEventPayload = v.object({
  $type: v.picklist(['PostUpdated']),
  threadId: vThreadId,
  postId: vPostId,
  updatedBy: vUserId
});

export const vNotifiableEventPayloadThreadApprovedNotifiableEventPayload = v.object({
  $type: v.picklist(['ThreadApproved']),
  threadId: vThreadId,
  createdBy: vUserId,
  approvedBy: vUserId,
  approvedAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vNotifiableEventPayloadThreadRejectedNotifiableEventPayload = v.object({
  $type: v.picklist(['ThreadRejected']),
  threadId: vThreadId,
  createdBy: vUserId,
  rejectedBy: vUserId,
  rejectedAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vNotifiableEventPayload = v.union([
  v.intersect([v.object({
      $type: v.literal('PostAdded')
    }), vNotifiableEventPayloadPostAddedNotifiableEventPayload]),
  v.intersect([v.object({
      $type: v.literal('PostUpdated')
    }), vNotifiableEventPayloadPostUpdatedNotifiableEventPayload]),
  v.intersect([v.object({
      $type: v.literal('ThreadApproved')
    }), vNotifiableEventPayloadThreadApprovedNotifiableEventPayload]),
  v.intersect([v.object({
      $type: v.literal('ThreadRejected')
    }), vNotifiableEventPayloadThreadRejectedNotifiableEventPayload])
]);

export const vInternalNotificationDto = v.object({
  notifiableEventId: vNotifiableEventId,
  payload: vNotifiableEventPayload,
  occurredAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value))),
  deliveredAt: v.nullish(v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value))))
});

export const vNotificationNotFoundError = v.object({
  $type: v.pipe(v.literal('NotificationNotFoundError'), v.readonly()),
  userId: vUserId,
  notifiableEventId: vNotifiableEventId,
  channel: vChannelType
});

export const vPagedListOfThreadDto = v.object({
  items: v.array(vThreadDto),
  totalCount: vCount
});

export const vThreadSubscriptionLatestEventDto = v.object({
  notifiableEventId: vNotifiableEventId,
  payload: vNotifiableEventPayload,
  occurredAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vThreadSubscriptionNotFoundError = v.object({
  $type: v.pipe(v.literal('ThreadSubscriptionNotFoundError'), v.readonly()),
  userId: vUserId,
  threadId: vThreadId
});

export const vUsername = v.pipe(v.string(), v.minLength(3), v.maxLength(64), v.regex(/^[a-z0-9]+(_[a-z0-9]+)*$/));

export const vInternalNotificationsPagedDto = v.object({
  notifications: v.array(vInternalNotificationDto),
  threads: v.record(vThreadId, vThreadTitle),
  users: v.record(vUserId, vUsername),
  totalCount: vCount
});

export const vGetUsersPagedQuerySortType = v.optional(v.picklist(['userId', '-userId']), 'userId');

export const vLocale = v.picklist(['en', 'ru']);

export const vChangeCurrentUserLocaleRequestBody = v.object({
  locale: vLocale
});

export const vUserDto = v.object({
  userId: vUserId,
  username: vUsername,
  email: v.string(),
  enabled: v.boolean(),
  createdAt: v.pipe(v.string(), v.isoTimestamp(), v.transform(value => new Date(value)))
});

export const vUserNotFoundError = v.object({
  $type: v.pipe(v.literal('UserNotFoundError'), v.readonly())
});

export const vCategoryNotFoundErrorWritable = v.object({
  categoryId: vCategoryId
});

export const vClaimNotFoundErrorWritable = v.object({
  claimName: v.string()
});

export const vDuplicatePostBookmarkErrorWritable = v.object({
  userId: vUserId,
  postId: vPostId
});

export const vLocaleRequiredErrorWritable = v.object({
  supportedLocales: v.array(v.string())
});

export const vNonPostAuthorErrorWritable = v.object({
  threadId: vThreadId,
  postId: vPostId
});

export const vPostBookmarkNotFoundErrorWritable = v.object({
  userId: vUserId,
  postId: vPostId
});

export const vPostStaleErrorWritable = v.object({
  threadId: vThreadId,
  postId: vPostId,
  rowVersion: vRowVersion
});

export const vThreadLockedByStateErrorWritable = v.object({
  state: vThreadState
});

export const vThreadNotInStateErrorWritable = v.object({
  state: vThreadState
});

export const vUnsupportedLocaleErrorWritable = v.object({
  supportedLocales: v.array(v.string())
});

export const vInvalidAvatarFileSizeErrorWritable = v.object({
  minimumFileSize: v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
  ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
  maximumFileSize: v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
  ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
  actualFileSize: v.pipe(v.union([
    v.number(),
    v.string(),
    v.bigint()
  ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vInvalidAvatarFileTypeErrorWritable = v.object({
  expectedMediaType: v.string()
});

export const vDuplicateThreadSubscriptionErrorWritable = v.object({
  userId: vUserId,
  threadId: vThreadId
});

export const vNotificationNotFoundErrorWritable = v.object({
  userId: vUserId,
  notifiableEventId: vNotifiableEventId,
  channel: vChannelType
});

export const vThreadSubscriptionNotFoundErrorWritable = v.object({
  userId: vUserId,
  threadId: vThreadId
});

export const vGetForumsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetForumsPagedQuery = v.object({
  title: v.optional(vForumTitle),
  createdBy: v.optional(vUserId),
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetForumsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetForumsPagedResponse = v.array(vForumDto);

export const vCreateForumBody = vCreateForumRequestBody;

export const vCreateForumHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

/**
 * Created
 */
export const vCreateForumResponse = vForumId;

export const vGetForumsCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetForumsCountQuery = v.object({
  createdBy: v.optional(vUserId)
});

/**
 * OK
 */
export const vGetForumsCountResponse = vCount;

export const vGetForumHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetForumPath = v.object({
  forumId: vForumId
});

/**
 * OK
 */
export const vGetForumResponse = vForumDto;

export const vGetForumsBulkHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetForumsBulkPath = v.object({
  forumIds: v.pipe(v.array(vForumId), v.minLength(1))
});

/**
 * OK
 */
export const vGetForumsBulkResponse = v.record(vForumId, v.union([v.object({
    value: vForumDto
  }), v.object({
    error: vForumNotFoundError
  })]));

export const vGetForumsCategoriesCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetForumsCategoriesCountPath = v.object({
  forumIds: v.pipe(v.array(vForumId), v.minLength(1))
});

/**
 * OK
 */
export const vGetForumsCategoriesCountResponse = v.record(vForumId, v.union([v.object({
    value: vCount
  }), v.object({
    error: vForumNotFoundError
  })]));

export const vGetCategoriesPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoriesPagedQuery = v.object({
  forumIds: v.optional(v.pipe(v.array(vForumId), v.minLength(1))),
  title: v.optional(vCategoryTitle),
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(v.pipe(v.array(vGetCategoriesPagedQuerySortType), v.minLength(1)), ['categoryId'])
});

/**
 * OK
 */
export const vGetCategoriesPagedResponse = v.array(vCategoryDto);

export const vCreateCategoryBody = vCreateCategoryRequestBody;

export const vCreateCategoryHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

/**
 * Created
 */
export const vCreateCategoryResponse = vCategoryId;

export const vGetCategoryHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoryPath = v.object({
  categoryId: vCategoryId
});

/**
 * OK
 */
export const vGetCategoryResponse = vCategoryDto;

export const vGetCategoriesBulkHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoriesBulkPath = v.object({
  categoryIds: v.pipe(v.array(vCategoryId), v.minLength(1))
});

/**
 * OK
 */
export const vGetCategoriesBulkResponse = v.record(vCategoryId, v.union([v.object({
    value: vCategoryDto
  }), v.object({
    error: vCategoryNotFoundError
  })]));

export const vGetCategoriesPostsCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoriesPostsCountPath = v.object({
  categoryIds: v.pipe(v.array(vCategoryId), v.minLength(1))
});

/**
 * OK
 */
export const vGetCategoriesPostsCountResponse = v.record(vCategoryId, v.union([v.object({
    value: vCount
  }), v.object({
    error: vCategoryNotFoundError
  })]));

export const vGetCategoriesPostsLatestHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoriesPostsLatestPath = v.object({
  categoryIds: v.pipe(v.array(vCategoryId), v.minLength(1))
});

/**
 * OK
 */
export const vGetCategoriesPostsLatestResponse = v.record(vCategoryId, vPostDto);

export const vGetCategoriesThreadsCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoriesThreadsCountPath = v.object({
  categoryIds: v.pipe(v.array(vCategoryId), v.minLength(1))
});

export const vGetCategoriesThreadsCountQuery = v.object({
  state: v.optional(vThreadState)
});

/**
 * OK
 */
export const vGetCategoriesThreadsCountResponse = v.record(vCategoryId, v.union([v.object({
    value: vCount
  }), v.object({
    error: vCategoryNotFoundError
  })]));

export const vGetCategoryThreadsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetCategoryThreadsPagedPath = v.object({
  categoryId: vCategoryId
});

export const vGetCategoryThreadsPagedQuery = v.object({
  state: v.optional(vThreadState),
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetCategoryThreadsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetCategoryThreadsPagedResponse = v.array(vThreadDto);

export const vGetThreadsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadsPagedQuery = v.object({
  createdBy: v.optional(vUserId),
  status: v.optional(vThreadState),
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetThreadsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetThreadsPagedResponse = v.array(vThreadDto);

export const vCreateThreadBody = vCreateThreadRequestBody;

export const vCreateThreadHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

/**
 * Created
 */
export const vCreateThreadResponse = vThreadId;

export const vGetThreadsCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadsCountQuery = v.object({
  createdBy: v.optional(vUserId),
  status: v.optional(vThreadState)
});

/**
 * OK
 */
export const vGetThreadsCountResponse = vCount;

export const vGetThreadHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadPath = v.object({
  threadId: vThreadId
});

/**
 * OK
 */
export const vGetThreadResponse = vThreadDto;

export const vGetThreadsBulkHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadsBulkPath = v.object({
  threadIds: v.pipe(v.array(vThreadId), v.minLength(1))
});

/**
 * OK
 */
export const vGetThreadsBulkResponse = v.record(vThreadId, v.union([v.object({
    value: vThreadDto
  }), v.object({
    error: v.variant('$type', [vThreadNotFoundError, vPermissionDeniedError])
  })]));

export const vGetThreadPostsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadPostsPagedPath = v.object({
  threadId: vThreadId
});

export const vGetThreadPostsPagedQuery = v.object({
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetThreadPostsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetThreadPostsPagedResponse = v.array(vPostDto);

export const vCreatePostBody = vCreatePostRequestBody;

export const vCreatePostHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vCreatePostPath = v.object({
  threadId: vThreadId
});

/**
 * Created
 */
export const vCreatePostResponse = vPostId;

export const vGetThreadsPostsCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadsPostsCountPath = v.object({
  threadIds: v.pipe(v.array(vThreadId), v.minLength(1))
});

export const vGetThreadsPostsCountQuery = v.object({
  status: v.optional(vThreadState)
});

/**
 * OK
 */
export const vGetThreadsPostsCountResponse = v.record(vThreadId, v.union([v.object({
    value: vCount
  }), v.object({
    error: v.variant('$type', [vThreadNotFoundError, vPermissionDeniedError])
  })]));

export const vGetThreadsPostsLatestHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadsPostsLatestPath = v.object({
  threadIds: v.pipe(v.array(vThreadId), v.minLength(1))
});

/**
 * OK
 */
export const vGetThreadsPostsLatestResponse = v.record(vThreadId, v.union([v.object({
    value: vPostDto
  }), v.object({
    error: v.variant('$type', [
      vThreadNotFoundError,
      vPermissionDeniedError,
      vPostNotFoundError
    ])
  })]));

export const vRequestThreadApprovalHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vRequestThreadApprovalPath = v.object({
  threadId: vThreadId
});

/**
 * No Content
 */
export const vRequestThreadApprovalResponse = v.void();

export const vApproveThreadHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vApproveThreadPath = v.object({
  threadId: vThreadId
});

/**
 * No Content
 */
export const vApproveThreadResponse = v.void();

export const vRejectThreadHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vRejectThreadPath = v.object({
  threadId: vThreadId
});

/**
 * No Content
 */
export const vRejectThreadResponse = v.void();

export const vDeletePostHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vDeletePostPath = v.object({
  postId: vPostId
});

/**
 * No Content
 */
export const vDeletePostResponse = v.void();

export const vGetPostHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetPostPath = v.object({
  postId: vPostId
});

/**
 * OK
 */
export const vGetPostResponse = vPostDto;

export const vUpdatePostBody = vUpdatePostRequestBody;

export const vUpdatePostHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vUpdatePostPath = v.object({
  postId: vPostId
});

/**
 * No Content
 */
export const vUpdatePostResponse = v.void();

export const vGetPostIndexHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetPostIndexPath = v.object({
  postId: vPostId
});

/**
 * OK
 */
export const vGetPostIndexResponse = vIndex;

export const vGetBookmarkedPostIdsHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetBookmarkedPostIdsPath = v.object({
  postIds: v.pipe(v.array(vPostId), v.minLength(1))
});

/**
 * OK
 */
export const vGetBookmarkedPostIdsResponse2 = vGetBookmarkedPostIdsResponse;

export const vDeletePostBookmarkHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vDeletePostBookmarkPath = v.object({
  postId: vPostId
});

/**
 * No Content
 */
export const vDeletePostBookmarkResponse = v.void();

export const vCreatePostBookmarkHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vCreatePostBookmarkPath = v.object({
  postId: vPostId
});

/**
 * No Content
 */
export const vCreatePostBookmarkResponse = v.void();

export const vGetBookmarkedPostsCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetBookmarkedPostsCountPath = v.object({
  userId: vUserId
});

/**
 * OK
 */
export const vGetBookmarkedPostsCountResponse = vCount;

export const vGetBookmarkedPostsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetBookmarkedPostsPagedPath = v.object({
  userId: vUserId
});

export const vGetBookmarkedPostsPagedQuery = v.object({
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetBookmarkedPostsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetBookmarkedPostsPagedResponse = v.array(vPostDto);

export const vSearchHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vSearchQuery = v.object({
  term: vSearchTerm,
  type: v.optional(vSearchResultType),
  offset: v.optional(vPaginationOffset),
  sort: v.optional(vSearchQuerySortType),
  limit: v.optional(vPaginationLimitMin10Max100),
  cursor: v.optional(vSearchCursor)
});

/**
 * OK
 */
export const vSearchResponse = vSearchResultsDto;

export const vDeleteAvatarHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

/**
 * No Content
 */
export const vDeleteAvatarResponse = v.void();

export const vUploadAvatarBody = v.object({
  file: vIFormFile
});

export const vUploadAvatarHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

/**
 * No Content
 */
export const vUploadAvatarResponse = v.void();

export const vGetInternalNotificationCountHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetInternalNotificationCountQuery = v.object({
  isDelivered: v.optional(v.boolean())
});

/**
 * OK
 */
export const vGetInternalNotificationCountResponse = vCount;

export const vGetInternalNotificationsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetInternalNotificationsPagedQuery = v.object({
  isDelivered: v.optional(v.boolean()),
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(v.pipe(v.array(vGetInternalNotificationsPagedQuerySortType), v.minLength(1)), ['occurredAt'])
});

/**
 * OK
 */
export const vGetInternalNotificationsPagedResponse = vInternalNotificationsPagedDto;

export const vMarkInternalNotificationAsReadHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vMarkInternalNotificationAsReadPath = v.object({
  notifiableEventId: vNotifiableEventId
});

/**
 * No Content
 */
export const vMarkInternalNotificationAsReadResponse = v.void();

export const vDeleteInternalNotificationHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vDeleteInternalNotificationPath = v.object({
  notifiableEventId: vNotifiableEventId
});

/**
 * No Content
 */
export const vDeleteInternalNotificationResponse = v.void();

export const vGetThreadSubscriptionsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadSubscriptionsPagedPath = v.object({
  userId: vUserId
});

export const vGetThreadSubscriptionsPagedQuery = v.object({
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetThreadSubscriptionsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetThreadSubscriptionsPagedResponse = vPagedListOfThreadDto;

export const vGetThreadSubscriptionLatestEventsPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadSubscriptionLatestEventsPagedPath = v.object({
  userId: vUserId
});

export const vGetThreadSubscriptionLatestEventsPagedQuery = v.object({
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetThreadSubscriptionLatestEventsPagedQuerySortType)
});

/**
 * OK
 */
export const vGetThreadSubscriptionLatestEventsPagedResponse = v.array(vThreadSubscriptionLatestEventDto);

export const vGetThreadSubscriptionStatusHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetThreadSubscriptionStatusPath = v.object({
  userId: vUserId,
  threadId: vThreadId
});

/**
 * OK
 */
export const vGetThreadSubscriptionStatusResponse = vGetThreadSubscriptionStatusQueryResult;

export const vDeleteThreadSubscriptionHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vDeleteThreadSubscriptionPath = v.object({
  userId: vUserId,
  threadId: vThreadId
});

/**
 * No Content
 */
export const vDeleteThreadSubscriptionResponse = v.void();

export const vCreateThreadSubscriptionBody = vCreateThreadSubscriptionRequestBody;

export const vCreateThreadSubscriptionHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vCreateThreadSubscriptionPath = v.object({
  userId: vUserId,
  threadId: vThreadId
});

/**
 * No Content
 */
export const vCreateThreadSubscriptionResponse = v.void();

export const vChangeCurrentUserLocaleBody = vChangeCurrentUserLocaleRequestBody;

export const vChangeCurrentUserLocaleHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

/**
 * No Content
 */
export const vChangeCurrentUserLocaleResponse = v.void();

export const vGetUsersPagedHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetUsersPagedQuery = v.object({
  offset: v.optional(vPaginationOffset),
  limit: v.optional(vPaginationLimitMin10Max100),
  sort: v.optional(vGetUsersPagedQuerySortType)
});

/**
 * OK
 */
export const vGetUsersPagedResponse = v.array(vUserDto);

export const vGetUserHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetUserPath = v.object({
  userId: vUserId
});

/**
 * OK
 */
export const vGetUserResponse = vUserDto;

export const vGetUsersBulkHeaders = v.object({
  'Accept-Language': v.picklist(['en', 'ru'])
});

export const vGetUsersBulkPath = v.object({
  userIds: v.pipe(v.array(vUserId), v.minLength(1))
});

/**
 * OK
 */
export const vGetUsersBulkResponse = v.record(vUserId, v.union([v.object({
    value: vUserDto
  }), v.object({
    error: vUserNotFoundError
  })]));
