// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCategoryId = z.string().uuid().regex(/^(?!00000000-0000-0000-0000-000000000000$)/);

export const zForumId = z.string().uuid().regex(/^(?!00000000-0000-0000-0000-000000000000$)/);

export const zCategoryTitle = z.string().min(3).max(128).regex(/^(?!\s*$).+/);

export const zUserId = z.string().uuid().regex(/^(?!00000000-0000-0000-0000-000000000000$)/);

export const zCategoryDto = z.object({
    categoryId: zCategoryId,
    forumId: zForumId,
    title: zCategoryTitle,
    createdBy: zUserId,
    createdAt: z.string().datetime()
});

export const zCategoryNotFoundError = z.object({
    '$type': z.string().readonly(),
    categoryId: zCategoryId
});

/**
 * Типы каналов доставки уведомлений
 *
 * 0 = Internal (Внутренний канал)
 *
 * 1 = Email (Электронная почта)
 */
export const zChannelType = z.unknown();

export const zCreateCategoryRequestBody = z.object({
    forumId: zForumId,
    title: zCategoryTitle
});

export const zForumTitle = z.string().min(3).max(64).regex(/^(?!\s*$).+/);

export const zCreateForumRequestBody = z.object({
    title: zForumTitle
});

export const zPostContent = z.string().min(2).max(1024).regex(/^(?!\s*$).+/);

export const zCreatePostRequestBody = z.object({
    content: zPostContent
});

export const zThreadTitle = z.string().min(3).max(128).regex(/^(?!\s*$).+/);

export const zCreateThreadRequestBody = z.object({
    categoryId: zCategoryId,
    title: zThreadTitle
});

export const zCreateThreadSubscriptionRequestBody = z.object({
    channels: z.array(zChannelType)
});

export const zThreadId = z.string().uuid().regex(/^(?!00000000-0000-0000-0000-000000000000$)/);

export const zDuplicateThreadSubscriptionError = z.object({
    '$type': z.string().readonly(),
    userId: zUserId,
    threadId: zThreadId
});

/**
 *
 *
 * 0 = Category (Форум содержит разделы)
 *
 * 1 = Thread (Форум содержит темы)
 *
 * 2 = Post (Форум содержит сообщения)
 */
export const zForumContainsFilter = z.unknown();

export const zForumDto = z.object({
    forumId: zForumId,
    title: zForumTitle,
    createdBy: zUserId,
    createdAt: z.string().datetime()
});

export const zForumNotFoundError = z.object({
    '$type': z.string().readonly(),
    forumId: zForumId
});

/**
 *
 *
 * activity (Sort by Activity ascending)
 *
 * -activity (Sort by Activity descending)
 */
export const zGetCategoryThreadsQuerySortEnum = z.enum([
    'activity',
    '-activity'
]);

/**
 *
 *
 * 0 = Activity
 */
export const zGetCategoryThreadsQuerySortType = z.unknown();

/**
 *
 *
 * latestpost (Sort by LatestPost ascending)
 *
 * -latestpost (Sort by LatestPost descending)
 */
export const zGetForumsQuerySortEnum = z.enum([
    'latestpost',
    '-latestpost'
]);

/**
 *
 *
 * 0 = LatestPost
 */
export const zGetForumsQuerySortType = z.unknown();

/**
 *
 *
 * occurredat (Sort by OccurredAt ascending)
 *
 * deliveredat (Sort by DeliveredAt ascending)
 *
 * -occurredat (Sort by OccurredAt descending)
 *
 * -deliveredat (Sort by DeliveredAt descending)
 */
export const zGetInternalUserNotificationQuerySortEnum = z.enum([
    'occurredat',
    'deliveredat',
    '-occurredat',
    '-deliveredat'
]);

/**
 *
 *
 * 0 = OccurredAt
 *
 * 1 = DeliveredAt
 */
export const zGetInternalUserNotificationQuerySortType = z.unknown();

export const zGetThreadSubscriptionStatusQueryResult = z.object({
    isSubscribed: z.boolean()
});

export const zNotificationPayload = z.object({
    '$type': z.string()
});

export const zPostId = z.coerce.bigint().gte(BigInt(1));

export const zPostAddedNotificationPayload = zNotificationPayload.and(z.object({
    '$type': z.literal('PostAddedNotificationPayload')
})).and(z.object({
    threadId: zThreadId,
    postId: zPostId,
    createdBy: zUserId
}));

export const zPostUpdatedNotificationPayload = zNotificationPayload.and(z.object({
    '$type': z.literal('PostUpdatedNotificationPayload')
})).and(z.object({
    threadId: zThreadId,
    postId: zPostId,
    updatedBy: zUserId
}));

export const zNotificationId = z.string().uuid().regex(/^(?!00000000-0000-0000-0000-000000000000$)/);

export const zInternalUserNotificationDto = z.object({
    payload: z.union([
        zPostAddedNotificationPayload,
        zPostUpdatedNotificationPayload
    ]),
    occurredAt: z.string().datetime(),
    notificationId: zNotificationId,
    deliveredAt: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zInternalUserNotificationsDto = z.object({
    notifications: z.array(zInternalUserNotificationDto),
    threads: z.object({}),
    users: z.object({})
});

export const zNonPostAuthorError = z.object({
    '$type': z.string().readonly(),
    threadId: zThreadId,
    postId: zPostId
});

export const zNonThreadOwnerError = z.object({
    '$type': z.string().readonly(),
    threadId: zThreadId
});

export const zNotOwnerError = z.object({
    '$type': z.string().readonly()
});

export const zPostDto = z.object({
    threadId: zThreadId,
    postId: zPostId,
    content: zPostContent,
    createdBy: zUserId,
    createdAt: z.string().datetime(),
    updatedBy: zUserId,
    updatedAt: z.string().datetime(),
    rowVersion: z.number().int()
});

export const zPostNotFoundError = z.object({
    '$type': z.string().readonly(),
    threadId: zThreadId,
    postId: zPostId
});

export const zPostStaleError = z.object({
    '$type': z.string().readonly(),
    threadId: zThreadId,
    postId: zPostId,
    rowVersion: z.number().int()
});

/**
 *
 *
 * 0 = Ascending
 *
 * 1 = Descending
 */
export const zSortOrderType = z.unknown();

/**
 * Состояние темы
 *
 * 0 = Draft (Тема еще подготавливается автором)
 *
 * 1 = Published (Тема опубликована и доступна пользователям)
 */
export const zThreadStatus = z.unknown();

export const zThreadDto = z.object({
    threadId: zThreadId,
    categoryId: zCategoryId,
    title: zThreadTitle,
    createdBy: zUserId,
    createdAt: z.string().datetime(),
    nextPostId: zPostId,
    status: zThreadStatus
});

export const zThreadNotFoundError = z.object({
    '$type': z.string().readonly(),
    threadId: zThreadId
});

export const zThreadSubscriptionNotFoundError = z.object({
    '$type': z.string().readonly(),
    userId: zUserId,
    threadId: zThreadId
});

export const zUpdatePostRequestBody = z.object({
    content: zPostContent,
    rowVersion: z.number().int()
});

export const zUserDto = z.object({
    userId: zUserId,
    username: z.string(),
    email: z.string(),
    enabled: z.boolean(),
    createdAt: z.string().datetime()
});

export const zUserNotFoundError = z.object({
    '$type': z.string().readonly(),
    userId: zUserId
});

export const zGetCategoriesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional(),
        forumId: zForumId.optional(),
        title: zCategoryTitle.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetCategoriesResponse = z.array(zCategoryDto);

export const zCreateCategoryData = z.object({
    body: zCreateCategoryRequestBody,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zCreateCategoryResponse = zCategoryId;

export const zGetCategoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        categoryId: zCategoryId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetCategoryResponse = zCategoryDto;

export const zGetCategoriesPostsCountData = z.object({
    body: z.never().optional(),
    path: z.object({
        categoryIds: z.array(zCategoryId)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetCategoriesPostsCountResponse = z.object({});

export const zGetCategoriesPostsLatestData = z.object({
    body: z.never().optional(),
    path: z.object({
        categoryIds: z.array(zCategoryId)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetCategoriesPostsLatestResponse = z.object({});

export const zGetCategoriesThreadsCountData = z.object({
    body: z.never().optional(),
    path: z.object({
        categoryIds: z.array(zCategoryId)
    }),
    query: z.object({
        includeDraft: z.boolean().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetCategoriesThreadsCountResponse = z.object({});

export const zGetCategoryThreadsData = z.object({
    body: z.never().optional(),
    path: z.object({
        categoryId: zCategoryId
    }),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional(),
        sort: zGetCategoryThreadsQuerySortEnum.optional(),
        includeDraft: z.boolean().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetCategoryThreadsResponse = z.array(zThreadDto);

export const zGetForumsCountData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        createdBy: zUserId.optional(),
        contains: zForumContainsFilter.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetForumsCountResponse = z.coerce.bigint();

export const zGetForumsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional(),
        sort: zGetForumsQuerySortEnum.optional(),
        title: zForumTitle.optional(),
        createdBy: zUserId.optional(),
        contains: zForumContainsFilter.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetForumsResponse = z.array(zForumDto);

export const zCreateForumData = z.object({
    body: zCreateForumRequestBody,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zCreateForumResponse = zForumId;

export const zGetForumData = z.object({
    body: z.never().optional(),
    path: z.object({
        forumId: zForumId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetForumResponse = zForumDto;

export const zGetForumsCategoriesCountData = z.object({
    body: z.never().optional(),
    path: z.object({
        forumIds: z.array(zForumId)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetForumsCategoriesCountResponse = z.object({});

export const zGetForumsCategoriesLatestData = z.object({
    body: z.never().optional(),
    path: z.object({
        forumIds: z.array(zForumId)
    }),
    query: z.object({
        count: z.number().int().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetForumsCategoriesLatestResponse = z.object({});

export const zGetPostsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional(),
        threadId: zThreadId.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetPostsResponse = z.array(zPostDto);

export const zGetThreadsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional(),
        createdBy: zUserId.optional(),
        status: zThreadStatus.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetThreadsResponse = z.array(zThreadDto);

export const zCreateThreadData = z.object({
    body: zCreateThreadRequestBody,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zCreateThreadResponse = zThreadId;

export const zGetThreadsCountData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        createdBy: zUserId.optional(),
        status: zThreadStatus.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetThreadsCountResponse = z.coerce.bigint();

export const zGetThreadData = z.object({
    body: z.never().optional(),
    path: z.object({
        threadId: zThreadId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetThreadResponse = zThreadDto;

export const zGetThreadsPostsCountData = z.object({
    body: z.never().optional(),
    path: z.object({
        threadIds: z.array(zThreadId)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetThreadsPostsCountResponse = z.object({});

export const zGetThreadsPostsLatestData = z.object({
    body: z.never().optional(),
    path: z.object({
        threadIds: z.array(zThreadId)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetThreadsPostsLatestResponse = z.object({});

export const zGetPostOrderData = z.object({
    body: z.never().optional(),
    path: z.object({
        threadId: zThreadId,
        postId: zPostId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetPostOrderResponse = z.coerce.bigint();

export const zCreatePostData = z.object({
    body: zCreatePostRequestBody,
    path: z.object({
        threadId: zThreadId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zCreatePostResponse = zPostId;

export const zUpdatePostData = z.object({
    body: zUpdatePostRequestBody,
    path: z.object({
        threadId: zThreadId,
        postId: zPostId
    }),
    query: z.never().optional()
});

export const zDeleteAvatarData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zUploadAvatarData = z.object({
    body: z.object({
        file: z.string().optional()
    }).optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetThreadSubscriptionStatusData = z.object({
    body: z.never().optional(),
    path: z.object({
        threadId: zThreadId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetThreadSubscriptionStatusResponse = zGetThreadSubscriptionStatusQueryResult;

export const zDeleteThreadSubscriptionData = z.object({
    body: z.never().optional(),
    path: z.object({
        threadId: zThreadId
    }),
    query: z.never().optional()
});

/**
 * No Content
 */
export const zDeleteThreadSubscriptionResponse = z.void();

export const zCreateThreadSubscriptionData = z.object({
    body: zCreateThreadSubscriptionRequestBody,
    path: z.object({
        threadId: zThreadId
    }),
    query: z.never().optional()
});

export const zGetUserNotificationCountData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        isDelivered: z.boolean().optional(),
        channel: zChannelType.optional()
    }).optional()
});

/**
 * OK
 */
export const zGetUserNotificationCountResponse = z.number().int();

export const zGetUserNotificationData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional(),
        sort: z.array(zGetInternalUserNotificationQuerySortEnum).optional(),
        isDelivered: z.boolean().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetUserNotificationResponse = zInternalUserNotificationsDto;

export const zGetUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        offset: z.number().int().optional(),
        limit: z.number().int().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetUsersResponse = z.array(zUserDto);

export const zGetUserByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: zUserId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetUserByIdResponse = zUserDto;

export const zGetUsersByIdsData = z.object({
    body: z.never().optional(),
    path: z.object({
        userIds: z.array(zUserId)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetUsersByIdsResponse = z.array(zUserDto);