// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WriteApplicationDbContext))]
    [Migration("20260809222414_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notification_service")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.NotifiableEvent", b =>
                {
                    b.Property<Guid>("NotifiableEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("notifiable_event_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ThreadId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id")
                        .HasComputedColumnSql("CASE WHEN \"payload\" ? 'PostId' THEN (\"payload\"->>'ThreadId')::uuid END", true);

                    b.HasKey("NotifiableEventId")
                        .HasName("pk_notifiable_events");

                    b.HasIndex("ThreadId", "OccurredAt", "NotifiableEventId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_notifiable_events_post_thread_latest");

                    b.ToTable("notifiable_events", "notification_service");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotifiableEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("notifiable_event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.HasKey("NotifiableEventId", "UserId", "Channel")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "Channel", "DeliveredAt")
                        .HasDatabaseName("ix_notifications_user_id_channel_delivered_at");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "Channel", "DeliveredAt"), new[] { "NotifiableEventId" });

                    b.ToTable("notifications", "notification_service", t =>
                        {
                            t.HasCheckConstraint("CK_notifications_channel_Enum", "channel IN (0, 1)");
                        });
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.ThreadSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<short[]>("Channels")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("channels");

                    b.HasKey("UserId", "ThreadId")
                        .HasName("pk_thread_subscriptions");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_thread_subscriptions_thread_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_thread_subscriptions_user_id");

                    b.ToTable("thread_subscriptions", "notification_service");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.NotifiableEvent", "NotifiableEvent")
                        .WithMany()
                        .HasForeignKey("NotifiableEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_notifiable_events_notifiable_event_id");

                    b.Navigation("NotifiableEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
