<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ZiggyCreatures.FusionCache"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\UserService.Application\UserService.Application.csproj"/>
    </ItemGroup>

</Project>
