// <auto-generated />
using System;
using CoreService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WriteApplicationDbContext))]
    [Migration("20251005151033_AddedPolicies2")]
    partial class AddedPolicies2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core_service")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CategoryPolicySetId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_policy_set_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.HasIndex("CategoryPolicySetId")
                        .HasDatabaseName("ix_categories_category_policy_set_id");

                    b.HasIndex("ForumId")
                        .HasDatabaseName("ix_categories_forum_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_categories_title");

                    b.ToTable("categories", "core_service");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<byte>("Policy")
                        .HasColumnType("smallint")
                        .HasColumnName("policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.HasKey("UserId", "CategoryId", "Policy")
                        .HasName("pk_category_grants");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_grants_category_id");

                    b.ToTable("category_grants", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_category_grants_policy_Enum", "policy BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryPolicySet", b =>
                {
                    b.Property<Guid>("CategoryPolicySetId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_policy_set_id");

                    b.Property<byte>("Access")
                        .HasColumnType("smallint")
                        .HasColumnName("access");

                    b.Property<byte>("PostCreate")
                        .HasColumnType("smallint")
                        .HasColumnName("post_create");

                    b.Property<byte>("ThreadCreate")
                        .HasColumnType("smallint")
                        .HasColumnName("thread_create");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("CategoryPolicySetId")
                        .HasName("pk_category_policy_sets");

                    b.ToTable("category_policy_sets", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_category_policy_sets_access_Enum", "access BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_category_policy_sets_post_create_Enum", "post_create BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_category_policy_sets_thread_create_Enum", "thread_create BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryRestriction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<byte>("Policy")
                        .HasColumnType("smallint")
                        .HasColumnName("policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.HasKey("UserId", "CategoryId", "Policy")
                        .HasName("pk_category_restrictions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_restrictions_category_id");

                    b.ToTable("category_restrictions", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_category_restrictions_policy_Enum", "policy BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryThreadAddable", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.ToTable("categories", "core_service");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Forum", b =>
                {
                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ForumPolicySetId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_policy_set_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("ForumId")
                        .HasName("pk_forums");

                    b.HasIndex("ForumPolicySetId")
                        .HasDatabaseName("ix_forums_forum_policy_set_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_forums_title");

                    b.ToTable("forums", "core_service");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumCategoryAddable", b =>
                {
                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_id");

                    b.HasKey("ForumId")
                        .HasName("pk_forums");

                    b.ToTable("forums", "core_service");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_id");

                    b.Property<byte>("Policy")
                        .HasColumnType("smallint")
                        .HasColumnName("policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.HasKey("UserId", "ForumId", "Policy")
                        .HasName("pk_forum_grants");

                    b.HasIndex("ForumId")
                        .HasDatabaseName("ix_forum_grants_forum_id");

                    b.ToTable("forum_grants", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_forum_grants_policy_Enum", "policy BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumPolicySet", b =>
                {
                    b.Property<Guid>("ForumPolicySetId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_policy_set_id");

                    b.Property<byte>("Access")
                        .HasColumnType("smallint")
                        .HasColumnName("access");

                    b.Property<byte>("CategoryCreate")
                        .HasColumnType("smallint")
                        .HasColumnName("category_create");

                    b.Property<byte>("PostCreate")
                        .HasColumnType("smallint")
                        .HasColumnName("post_create");

                    b.Property<byte>("ThreadCreate")
                        .HasColumnType("smallint")
                        .HasColumnName("thread_create");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("ForumPolicySetId")
                        .HasName("pk_forum_policy_sets");

                    b.ToTable("forum_policy_sets", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_forum_policy_sets_access_Enum", "access BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_forum_policy_sets_category_create_Enum", "category_create BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_forum_policy_sets_post_create_Enum", "post_create BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_forum_policy_sets_thread_create_Enum", "thread_create BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumRestriction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_id");

                    b.Property<byte>("Policy")
                        .HasColumnType("smallint")
                        .HasColumnName("policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.HasKey("UserId", "ForumId", "Policy")
                        .HasName("pk_forum_restrictions");

                    b.HasIndex("ForumId")
                        .HasDatabaseName("ix_forum_restrictions_forum_id");

                    b.ToTable("forum_restrictions", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_forum_restrictions_policy_Enum", "policy BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("PostId")
                        .HasName("pk_posts");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_posts_thread_id");

                    b.HasIndex("ThreadId", "CreatedAt", "PostId")
                        .HasDatabaseName("ix_posts_thread_id_created_at_post_id");

                    b.ToTable("posts", "core_service");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Thread", b =>
                {
                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid?>("ThreadPolicySetId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_policy_set_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.HasKey("ThreadId")
                        .HasName("pk_threads");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_threads_category_id");

                    b.HasIndex("ThreadPolicySetId")
                        .HasDatabaseName("ix_threads_thread_policy_set_id");

                    b.ToTable("threads", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_threads_status_Enum", "status IN (0, 1)");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<byte>("Policy")
                        .HasColumnType("smallint")
                        .HasColumnName("policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.HasKey("UserId", "ThreadId", "Policy")
                        .HasName("pk_thread_grants");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_thread_grants_thread_id");

                    b.ToTable("thread_grants", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_thread_grants_policy_Enum", "policy BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadPolicySet", b =>
                {
                    b.Property<Guid>("ThreadPolicySetId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_policy_set_id");

                    b.Property<byte>("Access")
                        .HasColumnType("smallint")
                        .HasColumnName("access");

                    b.Property<byte>("PostCreate")
                        .HasColumnType("smallint")
                        .HasColumnName("post_create");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("ThreadPolicySetId")
                        .HasName("pk_thread_policy_sets");

                    b.ToTable("thread_policy_sets", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_thread_policy_sets_access_Enum", "access BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_thread_policy_sets_post_create_Enum", "post_create BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadPostAddable", b =>
                {
                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<Guid?>("CreatedBy")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("ThreadId")
                        .HasName("pk_threads");

                    b.ToTable("threads", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_threads_status_Enum", "status IN (0, 1)");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadRestriction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<byte>("Policy")
                        .HasColumnType("smallint")
                        .HasColumnName("policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.HasKey("UserId", "ThreadId", "Policy")
                        .HasName("pk_thread_restrictions");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_thread_restrictions_thread_id");

                    b.ToTable("thread_restrictions", "core_service", t =>
                        {
                            t.HasCheckConstraint("CK_thread_restrictions_policy_Enum", "policy BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Category", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.CategoryPolicySet", null)
                        .WithMany()
                        .HasForeignKey("CategoryPolicySetId")
                        .HasConstraintName("fk_categories_category_policy_sets_category_policy_set_id");

                    b.HasOne("CoreService.Domain.Entities.Forum", null)
                        .WithMany("Categories")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_forums_forum_id");

                    b.HasOne("CoreService.Domain.Entities.ForumCategoryAddable", null)
                        .WithMany("Categories")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_forums_forum_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryGrant", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_grants_categories_category_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryRestriction", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_restrictions_categories_category_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryThreadAddable", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Category", null)
                        .WithOne()
                        .HasForeignKey("CoreService.Domain.Entities.CategoryThreadAddable", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_categories_category_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Forum", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.ForumPolicySet", null)
                        .WithMany()
                        .HasForeignKey("ForumPolicySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forums_forum_policy_sets_forum_policy_set_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumCategoryAddable", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Forum", null)
                        .WithOne()
                        .HasForeignKey("CoreService.Domain.Entities.ForumCategoryAddable", "ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forums_forums_forum_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumGrant", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Forum", null)
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_grants_forums_forum_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumRestriction", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Forum", null)
                        .WithMany()
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_restrictions_forums_forum_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Post", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Thread", null)
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_threads_thread_id");

                    b.HasOne("CoreService.Domain.Entities.ThreadPostAddable", null)
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_threads_thread_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Thread", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Category", null)
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threads_categories_category_id");

                    b.HasOne("CoreService.Domain.Entities.CategoryThreadAddable", null)
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threads_categories_category_id");

                    b.HasOne("CoreService.Domain.Entities.ThreadPolicySet", null)
                        .WithMany()
                        .HasForeignKey("ThreadPolicySetId")
                        .HasConstraintName("fk_threads_thread_policy_sets_thread_policy_set_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadGrant", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thread_grants_threads_thread_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadPostAddable", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Thread", null)
                        .WithOne()
                        .HasForeignKey("CoreService.Domain.Entities.ThreadPostAddable", "ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_threads_threads_thread_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadRestriction", b =>
                {
                    b.HasOne("CoreService.Domain.Entities.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thread_restrictions_threads_thread_id");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Category", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.CategoryThreadAddable", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Forum", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ForumCategoryAddable", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.Thread", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CoreService.Domain.Entities.ThreadPostAddable", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
